using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;
using FontFamily = System.Windows.Media.FontFamily;
using SanmiToys.Core.Services;

namespace SanmiToys.Core.Services;

public record LanguageOption(string Code, string DisplayName, string NativeName);

public class LocalizationService : INotifyPropertyChanged
{
    private static readonly Lazy<LocalizationService> _instance = new(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    public event PropertyChangedEventHandler? PropertyChanged;
    public event Action? LanguageChanged;

    public static readonly IReadOnlyList<LanguageOption> SupportedLanguages = new List<LanguageOption>
    {
        new("auto", "System Default (自動)", "Auto"),
        new("ja", "日本語", "Japanese"),
        new("en", "English", "English"),
        new("zh-Hans", "简体中文", "Simplified Chinese"),
        new("zh-Hant", "繁體中文", "Traditional Chinese"),
        new("ko", "한국어", "Korean"),
        new("de", "Deutsch", "German"),
        new("fr", "Français", "French"),
        new("es", "Español", "Spanish")
    };

    private string _currentLanguageCode = "auto";
    private string _effectiveLanguageCode = "en";
    private FontFamily _currentFontFamily = new("Segoe UI Variable Text, Segoe UI, sans-serif");

    public string CurrentLanguageCode
    {
        get => _currentLanguageCode;
        set
        {
            if (_currentLanguageCode != value)
            {
                _currentLanguageCode = value;
                SettingsService.Instance.SetGeneralSetting("Language", value);
                UpdateEffectiveLanguage();
            }
        }
    }

    public string EffectiveLanguageCode => _effectiveLanguageCode;

    public FontFamily CurrentFontFamily => _currentFontFamily;

    public string this[string key] => GetString(key);

    public LocalizationService()
    {
        var saved = SettingsService.Instance.GetGeneralSetting("Language", "auto");
        _currentLanguageCode = saved;
        UpdateEffectiveLanguage();
    }

    private void UpdateEffectiveLanguage()
    {
        if (_currentLanguageCode == "auto")
        {
            var uiLang = CultureInfo.CurrentUICulture.Name;
            if (uiLang.StartsWith("ja", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "ja";
            else if (uiLang.StartsWith("zh-Hans", StringComparison.OrdinalIgnoreCase) || uiLang.Equals("zh-CN", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "zh-Hans";
            else if (uiLang.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "zh-Hant";
            else if (uiLang.StartsWith("ko", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "ko";
            else if (uiLang.StartsWith("de", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "de";
            else if (uiLang.StartsWith("fr", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "fr";
            else if (uiLang.StartsWith("es", StringComparison.OrdinalIgnoreCase))
                _effectiveLanguageCode = "es";
            else
                _effectiveLanguageCode = "en";
        }
        else
        {
            _effectiveLanguageCode = _currentLanguageCode;
        }

        // 各言語に最適なモダンUIフォントチェーンを設定
        _currentFontFamily = _effectiveLanguageCode switch
        {
            "ja" => new FontFamily("Segoe UI Variable Text, Yu Gothic UI, Meiryo UI, Segoe UI"),
            "zh-Hans" => new FontFamily("Segoe UI Variable Text, Microsoft YaHei UI, Segoe UI"),
            "zh-Hant" => new FontFamily("Segoe UI Variable Text, Microsoft JhengHei UI, Segoe UI"),
            "ko" => new FontFamily("Segoe UI Variable Text, Malgun Gothic, Segoe UI"),
            _ => new FontFamily("Segoe UI Variable Text, Segoe UI, Aptos, Inter, sans-serif")
        };

        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(EffectiveLanguageCode)));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentFontFamily)));
        LanguageChanged?.Invoke();
    }

    public string GetString(string key)
    {
        if (string.IsNullOrEmpty(key)) return string.Empty;

        if (_dictionaries.TryGetValue(_effectiveLanguageCode, out var dict) && dict.TryGetValue(key, out var val))
        {
            return val;
        }

        // Fallback to en
        if (_effectiveLanguageCode != "en" && _dictionaries.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enVal))
        {
            return enVal;
        }

        // Fallback to ja
        if (_effectiveLanguageCode != "ja" && _dictionaries.TryGetValue("ja", out var jaDict) && jaDict.TryGetValue(key, out var jaVal))
        {
            return jaVal;
        }

        return key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _dictionaries = new()
    {
        ["ja"] = new Dictionary<string, string>
        {
            // Navigation & Host
            ["Nav_Dashboard"] = "ダッシュボード",
            ["Nav_FluidDrag"] = "FluidDrag",
            ["Nav_FocusDimmer"] = "FocusDimmer",
            ["Nav_SnapTrans"] = "SnapTrans",
            ["Nav_SwiftVolume"] = "SwiftVolume",
            ["Nav_GeneralSettings"] = "全般設定",
            ["Nav_UpdateNow"] = "今すぐアップデート",
            ["Nav_UpdateVersion"] = "今すぐアップデート (v{0})",
            ["Nav_UpdatingProgress"] = "更新中 {0}%",
            ["Nav_ApplyingUpdate"] = "更新を適用中...",
            ["Nav_UpdateNotificationTitle"] = "SanmiToys アップデート",
            ["Nav_UpdateNotificationBody"] = "新しいバージョン (v{0}) が利用可能です。\nクリックしてアップデートを開きます。",

            // Dashboard
            ["Dashboard_Title"] = "SanmiToys",
            ["Dashboard_Subtitle"] = "デスクトップ作業を直感的・スマートにするモジュール型ユーティリティ スイート",
            ["Dashboard_EnabledModules"] = "ユーティリティ モジュール一覧",
            ["Dashboard_SettingsBtn"] = "設定",

            // General Settings
            ["General_Title"] = "全般設定",
            ["General_Subtitle"] = "SanmiToys の起動動作とシステム統合設定",
            ["General_LanguageSection"] = "言語設定",
            ["General_Language_Title"] = "表示言語",
            ["General_Language_Desc"] = "アプリケーション全体の表示言語を変更します",
            ["General_StartupSection"] = "起動と動作",
            ["General_Startup_Title"] = "Windows 起動時に自動実行",
            ["General_Startup_Desc"] = "PC起動時にバックグラウンドで自動的に開始します",
            ["General_MinimizeToTray_Title"] = "閉じるボタン（×）でタスクトレイに最小化",
            ["General_MinimizeToTray_Desc"] = "ウィンドウを閉じてもバックグラウンドでツールを継続動作させます",
            ["General_UpdatesSection"] = "アップデート",
            ["General_Updates_Title"] = "更新プログラムの確認",
            ["General_Updates_Desc"] = "最新の機能とセキュリティ修正を確認します",
            ["General_CheckUpdatesBtn"] = "更新の確認",
            ["General_CheckingUpdates"] = "更新を確認中...",
            ["General_ApplyUpdateBtn"] = "今すぐ更新して再起動",
            ["General_UpdatingMessage"] = "更新をダウンロード中... ({0}%)",
            ["General_UpToDate"] = "最新バージョンをご利用中です (v{0})",
            ["General_UpdateAvailable"] = "新しいバージョン (v{0}) が利用可能です！",
            ["General_UpdateError"] = "更新の確認に失敗しました。ネットワーク接続をご確認ください。",
            ["General_SupportSection"] = "開発者支援",
            ["General_Support_Subtitle"] = "SanmiToys がお役に立ちましたら、継続開発のサポートをぜひお願いいたします！",
            ["General_Support_JP_Title"] = "日本語向け支援 (OFUSE)",
            ["General_Support_JP_Desc"] = "OFUSE にて応援メッセージ付きで少額から投げ銭・支援いただけます",
            ["General_Support_JP_Btn"] = "OFUSE で支援する",
            ["General_Support_Global_Title"] = "海外・グローバル支援 (Buy Me a Coffee)",
            ["General_Support_Global_Desc"] = "Buy Me a Coffee からコーヒー1杯分の気軽なご支援が可能です",
            ["General_Support_Global_Btn"] = "Buy Me a Coffee",
            ["General_AboutSection"] = "バージョン情報",
            ["General_About_Author"] = "Created by sanmi / sanmiri",
            ["General_About_Framework"] = ".NET 8 / WPF-UI Fluent",

            // Tray
            ["Tray_OpenDashboard"] = "ダッシュボードを開く",
            ["Tray_Settings"] = "全般設定",
            ["Tray_Exit"] = "終了",

            // Common
            ["Common_Settings"] = "設定",
            ["Common_Enabled"] = "有効",
            ["Common_Disabled"] = "無効",
            ["Common_Clear"] = "クリア",
            ["Common_Close"] = "閉じる",
            ["Common_Copy"] = "コピー",
            ["Common_Save"] = "保存",
            ["Common_Cancel"] = "キャンセル",
            ["Common_Reset"] = "リセット",
            ["Common_Add"] = "追加",
            ["Common_Delete"] = "削除",
            ["Common_Select"] = "選択",
            ["Common_NotSet"] = "未設定 (クリックして入力)",
            ["Common_PressKeys"] = "キーを押してください...",

            // FluidDrag
            ["FluidDrag_Name"] = "FluidDrag",
            ["FluidDrag_Desc"] = "ウィンドウ内の空いている背景部分をクリック＆ドラッグしてウィンドウを自在に移動",
            ["FluidDrag_Subtitle"] = "ウィンドウ内の空いている背景部分をクリック＆ドラッグしてウィンドウを自在に移動",
            ["FluidDrag_Enable_Desc"] = "テキストやボタン、リンクなどの操作可能領域では通常操作が優先され、誤ドラッグを防ぎます。",
            ["FluidDrag_BehaviorSection"] = "ドラッグ操作の設定",
            ["FluidDrag_ModifierKey"] = "有効化キー",
            ["FluidDrag_ModifierKey_Desc"] = "押している間だけドラッグ移動を有効にします（「なし」で常時有効）",
            ["FluidDrag_ResizeKey"] = "無効化キー",
            ["FluidDrag_ResizeKey_Desc"] = "押している間だけドラッグ移動を一時的に無効にします（テキスト選択・通常クリック時など）",
            ["FluidDrag_Threshold"] = "ドラッグ開始の移動量しきい値",
            ["FluidDrag_Threshold_Desc"] = "クリック時のブレによる誤判定を防ぐための移動ピクセル数です",
            ["FluidDrag_ExclusionsSection"] = "動作の除外・制限",
            ["FluidDrag_ExcludeFullscreen"] = "ゲーム・フルスクリーンアプリで自動除外",
            ["FluidDrag_ExcludeFullscreen_Desc"] = "ゲームプレイ中や全画面表示時はドラッグ移動を完全に無効化します",
            ["FluidDrag_ExcludeMaximized"] = "最大化ウィンドウを除外",
            ["FluidDrag_ExcludeMaximized_Desc"] = "最大化されているウィンドウはドラッグ移動の対象から除外します",
            ["FluidDrag_RunningAppsSection"] = "起動中のアプリから選んで除外に追加",
            ["FluidDrag_RunningApps_Title"] = "現在実行中のウィンドウ一覧",
            ["FluidDrag_RunningApps_Desc"] = "開いているアプリ一覧からワンクリックで除外リストに追加できます",
            ["FluidDrag_RefreshAppsBtn"] = "一覧を更新",
            ["FluidDrag_AddRunningAppBtn"] = "除外リストに追加",
            ["FluidDrag_ProcessListSection"] = "除外プロセス一覧",
            ["FluidDrag_AddProcess_Title"] = "プロセス名の手動追加",
            ["FluidDrag_AddProcess_Desc"] = "特定の実行ファイル名（例: photoshop, blender, steam）を除外登録します",
            ["FluidDrag_AddProcess_Placeholder"] = "プロセス名 (例: steam)",
            ["FluidDrag_TitleListSection"] = "除外ウィンドウタイトルキーワード",
            ["FluidDrag_AddTitle_Title"] = "タイトルキーワードの手動追加",
            ["FluidDrag_AddTitle_Desc"] = "ウィンドウタイトルに指定の文字列が含まれる場合に除外します",
            ["FluidDrag_AddTitle_Placeholder"] = "キーワード (例: プレビュー)",
            ["FluidDrag_Mod_None"] = "なし（常に有効）",
            ["FluidDrag_Mod_NoneDisable"] = "なし（無効化キーなし）",
            ["FluidDrag_Mod_Alt"] = "Alt キー",
            ["FluidDrag_Mod_Win"] = "Win キー",
            ["FluidDrag_Mod_Ctrl"] = "Ctrl キー",
            ["FluidDrag_Mod_Shift"] = "Shift キー",

            // FocusDimmer
            ["FocusDimmer_Name"] = "FocusDimmer",
            ["FocusDimmer_Desc"] = "アクティブウィンドウ以外を美しく調光し、作業への没入感と集中力を最大化",
            ["FocusDimmer_Subtitle"] = "アクティブウィンドウ以外を美しく調光し、作業への没入感と集中力を最大化",
            ["FocusDimmer_Enable_Desc"] = "作業中のウィンドウに視線を集中させ、画面の眩しさや周囲のノイズを軽減します。",
            ["FocusDimmer_MultiMonitorSection"] = "マルチモニター設定",
            ["FocusDimmer_LinkMonitors"] = "全モニターの設定を連動する",
            ["FocusDimmer_LinkMonitors_Desc"] = "ONにすると、すべてのモニターに同一の減光設定が適用されます",
            ["FocusDimmer_TargetMonitor"] = "設定対象のモニター",
            ["FocusDimmer_TargetMonitor_Desc"] = "個別設定を行うモニターを選択してください",
            ["FocusDimmer_VisualSection"] = "減光・カラー設定",
            ["FocusDimmer_DimOpacity"] = "減光率（不透明度）",
            ["FocusDimmer_DimOpacity_Desc"] = "背景ウィンドウやデスクトップを暗くする強さを指定します",
            ["FocusDimmer_DimColor"] = "オーバーレイカラー",
            ["FocusDimmer_DimColor_Desc"] = "減光オーバーレイの色（モダンパレットから直感的に選択可能）",
            ["FocusDimmer_DimColor_Btn"] = "カラーパレットを開く",
            ["FocusDimmer_OptionsSection"] = "動作・除外オプション",
            ["FocusDimmer_DimDesktopOnly"] = "デスクトップのみを減光",
            ["FocusDimmer_DimDesktopOnly_Desc"] = "他の全アプリウィンドウは明るく表示し、壁紙・デスクトップアイコンのみを暗くします",
            ["FocusDimmer_ExcludeTaskbar"] = "タスクバーを除外",
            ["FocusDimmer_ExcludeTaskbar_Desc"] = "タスクバーは減光せず常に明るく表示します",
            ["FocusDimmer_ExcludeTopmost"] = "最前面ウィンドウを除外",
            ["FocusDimmer_ExcludeTopmost_Desc"] = "常に手前に表示されるピクチャーインピクチャーやツールを除外します",
            ["FocusDimmer_IdleSection"] = "アイドル減光",
            ["FocusDimmer_IdleDim"] = "無操作時のアイドル減光を有効化",
            ["FocusDimmer_IdleDim_Desc"] = "一定時間マウスやキーボードの操作がない場合、画面全体をさらに減光します",
            ["FocusDimmer_IdleTimeout"] = "アイドル判定時間 (分)",
            ["FocusDimmer_IdleTimeout_Desc"] = "減光を開始するまでの無操作時間（分）",
            ["FocusDimmer_IdleOpacity"] = "アイドル時の減光率",
            ["FocusDimmer_IdleOpacity_Desc"] = "アイドル中に適用する強い減光の強さ",
            ["FocusDimmer_RulesSection"] = "プロセス別ルール",
            ["FocusDimmer_Inspector_Title"] = "ウィンドウ インスペクター",
            ["FocusDimmer_Inspector_Desc"] = "画面上の任意のウィンドウをクリックして、プロセス名やウィンドウ情報を調査・自動登録します",
            ["FocusDimmer_Inspector_Status"] = "左クリックでリストを固定 / Escで終了",
            ["FocusDimmer_InspectorBtn"] = "インスペクターを起動",
            ["FocusDimmer_AlwaysBright_Title"] = "常時明るくするアプリ",
            ["FocusDimmer_AlwaysBright_Desc"] = "バックグラウンドにあっても減光しないプロセス名（例: obs64, discord）",
            ["FocusDimmer_AlwaysDark_Title"] = "常時減光するアプリ",
            ["FocusDimmer_AlwaysDark_Desc"] = "アクティブ時でも減光を維持するオーバーレイ等のプロセス名",
            
            // FocusDimmer Dialogs & Subwindows
            ["InspectorAction_Title"] = "ルールの追加",
            ["InspectorAction_Heading"] = "ウィンドウ アクション",
            ["InspectorAction_AlwaysBright"] = "常時明るくするリストに追加",
            ["InspectorAction_AlwaysDark"] = "常時減光するリストに追加",
            ["InspectorAction_CopyProcess"] = "プロセス名をクリップボードにコピー",
            ["ColorPicker_Title"] = "カラーパレット",
            ["ColorPicker_Palette"] = "モダン プリセット パレット",
            ["ColorPicker_CustomHex"] = "カスタム HEX コード",
            ["Color_Black"] = "ピュアブラック (#000000)",
            ["Color_Dark"] = "ダークスレート (#121212)",
            ["Color_Midnight"] = "ミッドナイトブルー (#0B132B)",
            ["Color_Warm"] = "ウォームチャコール (#1C1917)",
            ["Color_Purple"] = "ディープパープル (#1E102F)",
            ["Color_Forest"] = "フォレストダーク (#064E3B)",
            ["Color_Blue"] = "ネイビーブルー (#1E3A8A)",

            // SnapTrans
            ["SnapTrans_Name"] = "SnapTrans",
            ["SnapTrans_Desc"] = "画面上のテキストを矩形選択してOCR文字認識＆即時翻訳・読み上げ",
            ["SnapTrans_Subtitle"] = "画面上のテキストを矩形選択してOCR文字認識＆即時翻訳・読み上げ",
            ["SnapTrans_Enable_Desc"] = "ショートカットキーまたはクイックトリガーで、画像やゲーム画面、Web上のテキストを範囲選択して即座に翻訳します。",
            ["SnapTrans_ShortcutSection"] = "ショートカットキー設定",
            ["SnapTrans_CaptureHotkey"] = "キャプチャ開始ホットキー",
            ["SnapTrans_CaptureHotkey_Desc"] = "ボックスをクリックして任意のキー（Ctrl, Alt, Shift, Win + キー）を押すと登録されます",
            ["SnapTrans_TranslationSection"] = "翻訳エンジン・言語設定",
            ["SnapTrans_Provider"] = "翻訳プロバイダー",
            ["SnapTrans_Provider_Desc"] = "使用する翻訳サービス（Google Web無料版、DeepL、Gemini、OpenAI）を選択します",
            ["SnapTrans_TargetLang"] = "翻訳先言語",
            ["SnapTrans_TargetLang_Desc"] = "翻訳後の出力言語を指定します",
            ["SnapTrans_ApiSection"] = "API キー設定",
            ["SnapTrans_DeepLKey"] = "DeepL API キー",
            ["SnapTrans_DeepLKey_Desc"] = "DeepL API (Free / Pro) の認証キー",
            ["SnapTrans_GeminiKey"] = "Gemini API キー",
            ["SnapTrans_GeminiKey_Desc"] = "Google AI Studio から取得した API キー",
            ["SnapTrans_OpenAiKey"] = "OpenAI API キー",
            ["SnapTrans_OpenAiKey_Desc"] = "OpenAI Platform の API キー",
            ["SnapTrans_BehaviorSection"] = "動作・クリップボード設定",
            ["SnapTrans_AutoCopy"] = "自動でクリップボードにコピー",
            ["SnapTrans_AutoCopy_Desc"] = "切り抜き完了時にテキストを自動的にクリップボードにコピーします",
            ["SnapTrans_CopySource"] = "翻訳前テキスト (原文 / OCR)",
            ["SnapTrans_CopySource_Desc"] = "OCRで認識した元のテキストをクリップボードにコピーします",
            ["SnapTrans_CopyTranslated"] = "翻訳後テキスト",
            ["SnapTrans_CopyTranslated_Desc"] = "翻訳完了後のテキストをクリップボードにコピーします",
            ["SnapTrans_AutoSpeak"] = "翻訳結果の自動音声読み上げ",
            ["SnapTrans_AutoSpeak_Desc"] = "翻訳完了と同時にテキストを音声で読み上げます",
            ["SnapTrans_TestSection"] = "テスト実行",
            ["SnapTrans_Test_Title"] = "今すぐスニッピング翻訳を試す",
            ["SnapTrans_Test_Desc"] = "画面上の領域を選択して翻訳テストを実行します",
            ["SnapTrans_Test_Btn"] = "領域選択を開始",
            ["SnapTrans_ToolTip_Speak"] = "読み上げ",
            ["SnapTrans_ToolTip_CopyTrans"] = "翻訳テキストをコピー",
            ["SnapTrans_ToolTip_Close"] = "閉じる",
            ["SnapTrans_Snip_Hint"] = "ドラッグして範囲を選択 | Esc でキャンセル",

            // SwiftVolume
            ["SwiftVolume_Name"] = "SwiftVolume",
            ["SwiftVolume_Desc"] = "タスクバー独立トレイアイコン、フライアウトミキサー、ホイール音量調節＆HUD",
            ["SwiftVolume_Subtitle"] = "タスクバー独立トレイアイコン、フライアウトミキサー、ホイール音量調節＆HUD",
            ["SwiftVolume_Enable_Desc"] = "有効化すると、タスクトレイに専用のスピーカーアイコンが表示され、クリックで音量ミキサーがポップアップします。",
            ["SwiftVolume_ControlSection"] = "タスクトレイ & ミキサー動作",
            ["SwiftVolume_OpenAtCursor"] = "ミキサーをカーソル位置に開く",
            ["SwiftVolume_OpenAtCursor_Desc"] = "トレイアイコンをクリックした際、マウスカーソルの直上にミキサーを開きます",
            ["SwiftVolume_MiddleClickMute"] = "トレイアイコン中クリックでミュート",
            ["SwiftVolume_MiddleClickMute_Desc"] = "スピーカー／マイクトレイアイコンをホイールクリックした際に即時ミュートします",
            ["SwiftVolume_HudSection"] = "HUD（オーバーレイ表示）設定",
            ["SwiftVolume_ShowHud"] = "音量HUDを表示",
            ["SwiftVolume_ShowHud_Desc"] = "音量調節時に現在の音量レベルを示すスタイリッシュなHUDを表示します",
            ["SwiftVolume_ShowDeviceSwitchHud"] = "デバイス切り替え時にHUD通知",
            ["SwiftVolume_ShowDeviceSwitchHud_Desc"] = "既定のスピーカーやマイクを変更した際に画面上に切り替え先デバイス名を表示します",
            ["SwiftVolume_HudPosition"] = "HUD 表示位置",
            ["SwiftVolume_HudPosition_Desc"] = "画面中央や各方向の角など、HUD を表示する位置を指定します",
            ["SwiftVolume_HudPos_Center"] = "画面中央",
            ["SwiftVolume_HudPos_TopCenter"] = "上部中央",
            ["SwiftVolume_HudPos_BottomCenter"] = "下部中央",
            ["SwiftVolume_HudPos_TopLeft"] = "左上",
            ["SwiftVolume_HudPos_TopRight"] = "右上",
            ["SwiftVolume_HudPos_BottomLeft"] = "左下",
            ["SwiftVolume_HudPos_BottomRight"] = "右下",
            ["SwiftVolume_HudSize"] = "HUD サイズ",
            ["SwiftVolume_HudSize_Desc"] = "画面に表示されるHUDの拡大縮小サイズを指定します",
            ["SwiftVolume_HudSize_Small"] = "小",
            ["SwiftVolume_HudSize_Medium"] = "中",
            ["SwiftVolume_HudSize_Large"] = "大",
            ["SwiftVolume_HotkeysSection"] = "ショートカットキー設定（キーボード）",
            ["SwiftVolume_Hotkey_OpenMixer"] = "音量ミキサーを開く",
            ["SwiftVolume_Hotkey_OpenMixer_Desc"] = "フライアウト音量ミキサーを即座にポップアップ表示するショートカットキー",
            ["SwiftVolume_Hotkey_Mute"] = "スピーカー ミュート切替",
            ["SwiftVolume_Hotkey_Mute_Desc"] = "マスター音声のミュート（消音）/ 解除を切り替えます",
            ["SwiftVolume_Hotkey_MicMute"] = "マイク ミュート切替",
            ["SwiftVolume_Hotkey_MicMute_Desc"] = "デフォルトマイクのミュート（消音）/ 解除を切り替えます",
            ["SwiftVolume_TestSection"] = "テスト操作",
            ["SwiftVolume_TestMixer_Title"] = "音量ミキサーのテスト表示",
            ["SwiftVolume_TestMixer_Desc"] = "フライアウトミキサーUIを今すぐ画面に表示します",
            ["SwiftVolume_ShowMixerBtn"] = "ミキサーを表示",
            ["SwiftVolume_Mixer_Tooltip_MuteSpeaker"] = "スピーカー ミュート切替",
            ["SwiftVolume_Mixer_Tooltip_Expand"] = "全デバイスミキサーの展開/折りたたみ",
            ["SwiftVolume_Mixer_Tooltip_MuteMic"] = "マイク ミュート切替",
            ["SwiftVolume_Hud_SpeakerSwitch"] = "スピーカー切替",
            ["SwiftVolume_Hud_MicSwitch"] = "マイク切替",
            ["SwiftVolume_Hud_MicMuted"] = "マイク ミュート",
            ["SwiftVolume_Hud_MicUnmuted"] = "マイク ミュート解除",
            ["SwiftVolume_Tray_Speaker"] = "SwiftVolume スピーカー",
            ["SwiftVolume_Tray_Mic"] = "SwiftVolume マイク",
            ["SwiftVolume_Tray_OpenSettings"] = "SwiftVolume 設定"
        },

        ["en"] = new Dictionary<string, string>
        {
            // Navigation & Host
            ["Nav_Dashboard"] = "Dashboard",
            ["Nav_FluidDrag"] = "FluidDrag",
            ["Nav_FocusDimmer"] = "FocusDimmer",
            ["Nav_SnapTrans"] = "SnapTrans",
            ["Nav_SwiftVolume"] = "SwiftVolume",
            ["Nav_GeneralSettings"] = "General Settings",
            ["Nav_UpdateNow"] = "Update Now",
            ["Nav_UpdateVersion"] = "Update Now (v{0})",
            ["Nav_UpdatingProgress"] = "Updating {0}%",
            ["Nav_ApplyingUpdate"] = "Applying update...",
            ["Nav_UpdateNotificationTitle"] = "SanmiToys Update",
            ["Nav_UpdateNotificationBody"] = "A new version (v{0}) is available.\nClick to view update.",

            // Dashboard
            ["Dashboard_Title"] = "SanmiToys",
            ["Dashboard_Subtitle"] = "Modular utility suite designed for intuitive, seamless Windows productivity",
            ["Dashboard_EnabledModules"] = "Active Utility Modules",
            ["Dashboard_SettingsBtn"] = "Settings",

            // General Settings
            ["General_Title"] = "General Settings",
            ["General_Subtitle"] = "SanmiToys startup behavior and system integration settings",
            ["General_LanguageSection"] = "Language Settings",
            ["General_Language_Title"] = "Display Language",
            ["General_Language_Desc"] = "Change application UI display language",
            ["General_StartupSection"] = "Startup and Behavior",
            ["General_Startup_Title"] = "Run on Windows Startup",
            ["General_Startup_Desc"] = "Automatically start SanmiToys in the background when PC boots",
            ["General_MinimizeToTray_Title"] = "Minimize to System Tray on Close (×)",
            ["General_MinimizeToTray_Desc"] = "Keep tools running in background when main window is closed",
            ["General_UpdatesSection"] = "Updates",
            ["General_Updates_Title"] = "Check for Updates",
            ["General_Updates_Desc"] = "Check for the latest features, enhancements and security fixes",
            ["General_CheckUpdatesBtn"] = "Check for Updates",
            ["General_CheckingUpdates"] = "Checking for updates...",
            ["General_ApplyUpdateBtn"] = "Update & Restart Now",
            ["General_UpdatingMessage"] = "Downloading update... ({0}%)",
            ["General_UpToDate"] = "You're up to date! (v{0})",
            ["General_UpdateAvailable"] = "A new version (v{0}) is available!",
            ["General_UpdateError"] = "Failed to check for updates. Please verify your internet connection.",
            ["General_SupportSection"] = "Support the Developer",
            ["General_Support_Subtitle"] = "If you enjoy using SanmiToys, please consider supporting its continued development!",
            ["General_Support_JP_Title"] = "Japanese Support (OFUSE)",
            ["General_Support_JP_Desc"] = "Send donations and supportive messages via OFUSE",
            ["General_Support_JP_Btn"] = "Support on OFUSE",
            ["General_Support_Global_Title"] = "Global Support (Buy Me a Coffee)",
            ["General_Support_Global_Desc"] = "Buy a coffee to support development and new feature work",
            ["General_Support_Global_Btn"] = "Buy Me a Coffee",
            ["General_AboutSection"] = "About",
            ["General_About_Author"] = "Created by sanmi / sanmiri",
            ["General_About_Framework"] = ".NET 8 / WPF-UI Fluent",

            // Tray
            ["Tray_OpenDashboard"] = "Open Dashboard",
            ["Tray_Settings"] = "General Settings",
            ["Tray_Exit"] = "Exit",

            // Common
            ["Common_Settings"] = "Settings",
            ["Common_Enabled"] = "Enabled",
            ["Common_Disabled"] = "Disabled",
            ["Common_Clear"] = "Clear",
            ["Common_Close"] = "Close",
            ["Common_Copy"] = "Copy",
            ["Common_Save"] = "Save",
            ["Common_Cancel"] = "Cancel",
            ["Common_Reset"] = "Reset",
            ["Common_Add"] = "Add",
            ["Common_Delete"] = "Delete",
            ["Common_Select"] = "Select",
            ["Common_NotSet"] = "Not Set (Click to set)",
            ["Common_PressKeys"] = "Press keys...",

            // FluidDrag
            ["FluidDrag_Name"] = "FluidDrag",
            ["FluidDrag_Desc"] = "Grab and move any window effortlessly by clicking and dragging empty background areas",
            ["FluidDrag_Subtitle"] = "Grab and move any window effortlessly by clicking and dragging empty background areas",
            ["FluidDrag_Enable_Desc"] = "Interactive UI elements like buttons, inputs and links retain normal behavior to avoid unwanted drags.",
            ["FluidDrag_BehaviorSection"] = "Drag Behavior Settings",
            ["FluidDrag_ModifierKey"] = "Activation Key",
            ["FluidDrag_ModifierKey_Desc"] = "Key to hold to enable window dragging (Select 'None' for always enabled)",
            ["FluidDrag_ResizeKey"] = "Disable Key",
            ["FluidDrag_ResizeKey_Desc"] = "Key to temporarily disable dragging while held (e.g. for text selection)",
            ["FluidDrag_Threshold"] = "Drag Start Threshold",
            ["FluidDrag_Threshold_Desc"] = "Movement threshold in pixels before initiating window drag",
            ["FluidDrag_ExclusionsSection"] = "Exclusions & Constraints",
            ["FluidDrag_ExcludeFullscreen"] = "Auto Exclude Games & Fullscreen Apps",
            ["FluidDrag_ExcludeFullscreen_Desc"] = "Completely disables window drag during games or fullscreen media",
            ["FluidDrag_ExcludeMaximized"] = "Exclude Maximized Windows",
            ["FluidDrag_ExcludeMaximized_Desc"] = "Prevents dragging windows that are currently maximized",
            ["FluidDrag_RunningAppsSection"] = "Pick from Running Windows",
            ["FluidDrag_RunningApps_Title"] = "Currently Open Windows",
            ["FluidDrag_RunningApps_Desc"] = "Easily add active apps to the exclusion list with one click",
            ["FluidDrag_RefreshAppsBtn"] = "Refresh List",
            ["FluidDrag_AddRunningAppBtn"] = "Add to Exclusion",
            ["FluidDrag_ProcessListSection"] = "Excluded Processes List",
            ["FluidDrag_AddProcess_Title"] = "Add Process Name Manually",
            ["FluidDrag_AddProcess_Desc"] = "Exclude specific executable names (e.g., photoshop, blender, steam)",
            ["FluidDrag_AddProcess_Placeholder"] = "Process Name (e.g., steam)",
            ["FluidDrag_TitleListSection"] = "Excluded Window Title Keywords",
            ["FluidDrag_AddTitle_Title"] = "Add Title Keyword Manually",
            ["FluidDrag_AddTitle_Desc"] = "Exclude windows containing specific keyword in their title",
            ["FluidDrag_AddTitle_Placeholder"] = "Keyword (e.g., Preview)",
            ["FluidDrag_Mod_None"] = "None (Always Active)",
            ["FluidDrag_Mod_NoneDisable"] = "None (No Disable Key)",
            ["FluidDrag_Mod_Alt"] = "Alt Key",
            ["FluidDrag_Mod_Win"] = "Win Key",
            ["FluidDrag_Mod_Ctrl"] = "Ctrl Key",
            ["FluidDrag_Mod_Shift"] = "Shift Key",

            // FocusDimmer
            ["FocusDimmer_Name"] = "FocusDimmer",
            ["FocusDimmer_Desc"] = "Elegantly dims inactive background windows to maximize immersion and productivity",
            ["FocusDimmer_Subtitle"] = "Elegantly dims inactive background windows to maximize immersion and productivity",
            ["FocusDimmer_Enable_Desc"] = "Maintains visual focus on the active task while reducing screen glare and peripheral distraction.",
            ["FocusDimmer_MultiMonitorSection"] = "Multi-Monitor Settings",
            ["FocusDimmer_LinkMonitors"] = "Sync Settings Across All Monitors",
            ["FocusDimmer_LinkMonitors_Desc"] = "Apply identical dimming settings to all connected displays",
            ["FocusDimmer_TargetMonitor"] = "Target Display",
            ["FocusDimmer_TargetMonitor_Desc"] = "Select monitor to configure individual dimming rules",
            ["FocusDimmer_VisualSection"] = "Dimming & Color Palette",
            ["FocusDimmer_DimOpacity"] = "Dimming Opacity",
            ["FocusDimmer_DimOpacity_Desc"] = "Opacity level applied to background windows and desktop",
            ["FocusDimmer_DimColor"] = "Dim Overlay Color",
            ["FocusDimmer_DimColor_Desc"] = "Overlay color tint (choose from modern curated palette)",
            ["FocusDimmer_DimColor_Btn"] = "Open Color Palette",
            ["FocusDimmer_OptionsSection"] = "Behavior & Exclusion Options",
            ["FocusDimmer_DimDesktopOnly"] = "Dim Desktop & Wallpaper Only",
            ["FocusDimmer_DimDesktopOnly_Desc"] = "Keep all app windows undimmed and only darken desktop wallpaper and icons",
            ["FocusDimmer_ExcludeTaskbar"] = "Exclude Taskbar",
            ["FocusDimmer_ExcludeTaskbar_Desc"] = "Keep taskbar always bright and visible",
            ["FocusDimmer_ExcludeTopmost"] = "Exclude Always-On-Top Windows",
            ["FocusDimmer_ExcludeTopmost_Desc"] = "Keep PiP players and floating tools undimmed",
            ["FocusDimmer_IdleSection"] = "Idle Dimming",
            ["FocusDimmer_IdleDim"] = "Enable Idle Dimming on Inactivity",
            ["FocusDimmer_IdleDim_Desc"] = "Darken the entire screen when no mouse or keyboard activity is detected",
            ["FocusDimmer_IdleTimeout"] = "Idle Timeout (Minutes)",
            ["FocusDimmer_IdleTimeout_Desc"] = "Inactivity threshold before idle dimming begins",
            ["FocusDimmer_IdleOpacity"] = "Idle Dimming Intensity",
            ["FocusDimmer_IdleOpacity_Desc"] = "Dimming opacity applied during idle state",
            ["FocusDimmer_RulesSection"] = "App Specific Rules",
            ["FocusDimmer_Inspector_Title"] = "Window Inspector",
            ["FocusDimmer_Inspector_Desc"] = "Click on any window on screen to inspect details and add to rules",
            ["FocusDimmer_Inspector_Status"] = "Left-click to pin list / Esc to exit",
            ["FocusDimmer_InspectorBtn"] = "Launch Inspector",
            ["FocusDimmer_AlwaysBright_Title"] = "Always Bright Apps",
            ["FocusDimmer_AlwaysBright_Desc"] = "Process names that should never be dimmed (e.g., obs64, discord)",
            ["FocusDimmer_AlwaysDark_Title"] = "Always Dark Apps",
            ["FocusDimmer_AlwaysDark_Desc"] = "Process names that stay dimmed even when focused",

            // FocusDimmer Dialogs
            ["InspectorAction_Title"] = "Add Rule",
            ["InspectorAction_Heading"] = "Window Action",
            ["InspectorAction_AlwaysBright"] = "Add to Always Bright",
            ["InspectorAction_AlwaysDark"] = "Add to Always Dark",
            ["InspectorAction_CopyProcess"] = "Copy Process Name to Clipboard",
            ["ColorPicker_Title"] = "Color Palette",
            ["ColorPicker_Palette"] = "Modern Preset Palette",
            ["ColorPicker_CustomHex"] = "Custom HEX Code",
            ["Color_Black"] = "Pure Black (#000000)",
            ["Color_Dark"] = "Dark Slate (#121212)",
            ["Color_Midnight"] = "Midnight Blue (#0B132B)",
            ["Color_Warm"] = "Warm Charcoal (#1C1917)",
            ["Color_Purple"] = "Deep Purple (#1E102F)",
            ["Color_Forest"] = "Forest Dark (#064E3B)",
            ["Color_Blue"] = "Navy Blue (#1E3A8A)",

            // SnapTrans
            ["SnapTrans_Name"] = "SnapTrans",
            ["SnapTrans_Desc"] = "Snip screen regions for instant OCR text recognition, translation, and TTS",
            ["SnapTrans_Subtitle"] = "Snip screen regions for instant OCR text recognition, translation, and TTS",
            ["SnapTrans_Enable_Desc"] = "Instantly capture and translate text from images, videos, games, or web pages with global shortcuts.",
            ["SnapTrans_ShortcutSection"] = "Shortcut Key Settings",
            ["SnapTrans_CaptureHotkey"] = "Capture Hotkey",
            ["SnapTrans_CaptureHotkey_Desc"] = "Click box and press your desired shortcut combination (Ctrl, Alt, Shift, Win + Key)",
            ["SnapTrans_TranslationSection"] = "Translation Engine & Language",
            ["SnapTrans_Provider"] = "Translation Provider",
            ["SnapTrans_Provider_Desc"] = "Select translation service (Google Web Free, DeepL, Gemini, OpenAI)",
            ["SnapTrans_TargetLang"] = "Target Translation Language",
            ["SnapTrans_TargetLang_Desc"] = "Language to translate extracted text into",
            ["SnapTrans_ApiSection"] = "API Key Configuration",
            ["SnapTrans_DeepLKey"] = "DeepL API Key",
            ["SnapTrans_DeepLKey_Desc"] = "Authentication key for DeepL API (Free / Pro)",
            ["SnapTrans_GeminiKey"] = "Gemini API Key",
            ["SnapTrans_GeminiKey_Desc"] = "API key obtained from Google AI Studio",
            ["SnapTrans_OpenAiKey"] = "OpenAI API Key",
            ["SnapTrans_OpenAiKey_Desc"] = "API key from OpenAI Platform",
            ["SnapTrans_BehaviorSection"] = "Behavior & Clipboard Settings",
            ["SnapTrans_AutoCopy"] = "Auto Copy to Clipboard",
            ["SnapTrans_AutoCopy_Desc"] = "Automatically copy text to clipboard upon completion",
            ["SnapTrans_CopySource"] = "Source Text (Original / OCR)",
            ["SnapTrans_CopySource_Desc"] = "Copy OCR recognized source text to clipboard",
            ["SnapTrans_CopyTranslated"] = "Translated Text",
            ["SnapTrans_CopyTranslated_Desc"] = "Copy translated text to clipboard",
            ["SnapTrans_AutoSpeak"] = "Auto Text-to-Speech",
            ["SnapTrans_AutoSpeak_Desc"] = "Automatically read aloud the translation result via TTS",
            ["SnapTrans_TestSection"] = "Test Run",
            ["SnapTrans_Test_Title"] = "Test Snipping Translation",
            ["SnapTrans_Test_Desc"] = "Select an on-screen area to perform a live translation test",
            ["SnapTrans_Test_Btn"] = "Start Screen Snipping",
            ["SnapTrans_ToolTip_Speak"] = "Read Aloud",
            ["SnapTrans_ToolTip_CopyTrans"] = "Copy Translation",
            ["SnapTrans_ToolTip_Close"] = "Close",
            ["SnapTrans_Snip_Hint"] = "Drag to select area | Esc to cancel",

            // SwiftVolume
            ["SwiftVolume_Name"] = "SwiftVolume",
            ["SwiftVolume_Desc"] = "Taskbar tray icon, flyout volume mixer, wheel scrolling volume adjustment & HUD",
            ["SwiftVolume_Subtitle"] = "Taskbar tray icon, flyout volume mixer, wheel scrolling volume adjustment & HUD",
            ["SwiftVolume_Enable_Desc"] = "Enables dedicated taskbar tray speaker icons and instant pop-up volume mixer on click.",
            ["SwiftVolume_ControlSection"] = "Taskbar Tray & Mixer Behavior",
            ["SwiftVolume_OpenAtCursor"] = "Open Mixer at Cursor Position",
            ["SwiftVolume_OpenAtCursor_Desc"] = "Opens the mixer flyout directly above mouse cursor when tray icon is clicked",
            ["SwiftVolume_MiddleClickMute"] = "Middle Click Tray Icon to Mute",
            ["SwiftVolume_MiddleClickMute_Desc"] = "Wheel click speaker or microphone tray icon to instantly toggle mute",
            ["SwiftVolume_HudSection"] = "HUD (On-Screen Display) Settings",
            ["SwiftVolume_ShowHud"] = "Show Modern Volume HUD",
            ["SwiftVolume_ShowHud_Desc"] = "Display a sleek on-screen volume indicator when adjusting levels",
            ["SwiftVolume_ShowDeviceSwitchHud"] = "Show HUD on Audio Device Change",
            ["SwiftVolume_ShowDeviceSwitchHud_Desc"] = "Show on-screen notification when default audio output/input device switches",
            ["SwiftVolume_HudPosition"] = "HUD Screen Position",
            ["SwiftVolume_HudPosition_Desc"] = "Choose where the HUD indicator appears on screen",
            ["SwiftVolume_HudPos_Center"] = "Center",
            ["SwiftVolume_HudPos_TopCenter"] = "Top Center",
            ["SwiftVolume_HudPos_BottomCenter"] = "Bottom Center",
            ["SwiftVolume_HudPos_TopLeft"] = "Top Left",
            ["SwiftVolume_HudPos_TopRight"] = "Top Right",
            ["SwiftVolume_HudPos_BottomLeft"] = "Bottom Left",
            ["SwiftVolume_HudPos_BottomRight"] = "Bottom Right",
            ["SwiftVolume_HudSize"] = "HUD Size",
            ["SwiftVolume_HudSize_Desc"] = "Scale size of on-screen HUD display",
            ["SwiftVolume_HudSize_Small"] = "Small",
            ["SwiftVolume_HudSize_Medium"] = "Medium",
            ["SwiftVolume_HudSize_Large"] = "Large",
            ["SwiftVolume_HotkeysSection"] = "Keyboard Shortcut Settings",
            ["SwiftVolume_Hotkey_OpenMixer"] = "Open Volume Mixer",
            ["SwiftVolume_Hotkey_OpenMixer_Desc"] = "Shortcut key to open lightweight flyout volume mixer popup",
            ["SwiftVolume_Hotkey_Mute"] = "Toggle Speaker Mute",
            ["SwiftVolume_Hotkey_Mute_Desc"] = "Mute or unmute master audio output",
            ["SwiftVolume_Hotkey_MicMute"] = "Toggle Microphone Mute",
            ["SwiftVolume_Hotkey_MicMute_Desc"] = "Mute or unmute default microphone input",
            ["SwiftVolume_TestSection"] = "Test",
            ["SwiftVolume_TestMixer_Title"] = "Test Volume Mixer",
            ["SwiftVolume_TestMixer_Desc"] = "Display the flyout volume mixer UI immediately on screen",
            ["SwiftVolume_ShowMixerBtn"] = "Show Mixer",
            ["SwiftVolume_Mixer_Tooltip_MuteSpeaker"] = "Toggle Speaker Mute",
            ["SwiftVolume_Mixer_Tooltip_Expand"] = "Expand / Collapse All Devices",
            ["SwiftVolume_Mixer_Tooltip_MuteMic"] = "Toggle Mic Mute",
            ["SwiftVolume_Hud_SpeakerSwitch"] = "Speaker Switched",
            ["SwiftVolume_Hud_MicSwitch"] = "Microphone Switched",
            ["SwiftVolume_Hud_MicMuted"] = "Microphone Muted",
            ["SwiftVolume_Hud_MicUnmuted"] = "Microphone Unmuted",
            ["SwiftVolume_Tray_Speaker"] = "SwiftVolume Speaker",
            ["SwiftVolume_Tray_Mic"] = "SwiftVolume Mic",
            ["SwiftVolume_Tray_OpenSettings"] = "SwiftVolume Settings"
        },

        ["zh-Hans"] = new Dictionary<string, string>
        {
            ["Nav_Dashboard"] = "仪表板",
            ["Nav_FluidDrag"] = "FluidDrag",
            ["Nav_FocusDimmer"] = "FocusDimmer",
            ["Nav_SnapTrans"] = "SnapTrans",
            ["Nav_SwiftVolume"] = "SwiftVolume",
            ["Nav_GeneralSettings"] = "常规设置",
            ["Nav_UpdateNow"] = "立即更新",
            ["Nav_UpdateVersion"] = "立即更新 (v{0})",
            ["Nav_UpdatingProgress"] = "更新中 {0}%",
            ["Nav_ApplyingUpdate"] = "正在应用更新...",
            ["Nav_UpdateNotificationTitle"] = "SanmiToys 更新",
            ["Nav_UpdateNotificationBody"] = "发现新版本 (v{0})。\n点击查看更新。",

            ["Dashboard_Title"] = "SanmiToys",
            ["Dashboard_Subtitle"] = "让桌面工作更直观、流畅的模块化实用工具集",
            ["Dashboard_EnabledModules"] = "实用模块列表",
            ["Dashboard_SettingsBtn"] = "设置",

            ["General_Title"] = "常规设置",
            ["General_Subtitle"] = "SanmiToys 启动行为与系统集成设置",
            ["General_LanguageSection"] = "语言设置",
            ["General_Language_Title"] = "显示语言",
            ["General_Language_Desc"] = "更改应用程序的显示语言",
            ["General_StartupSection"] = "启动与行为",
            ["General_Startup_Title"] = "开机自动启动",
            ["General_Startup_Desc"] = "在 Windows 启动时自动在后台运行",
            ["General_MinimizeToTray_Title"] = "点击关闭（×）最小化到系统托盘",
            ["General_MinimizeToTray_Desc"] = "关闭窗口后工具仍在后台保持运行",
            ["General_UpdatesSection"] = "软件更新",
            ["General_Updates_Title"] = "检查更新",
            ["General_Updates_Desc"] = "检查最新功能与错误修复",
            ["General_CheckUpdatesBtn"] = "检查更新",
            ["General_CheckingUpdates"] = "正在检查更新...",
            ["General_ApplyUpdateBtn"] = "立即更新并重启",
            ["General_UpdatingMessage"] = "正在下载更新... ({0}%)",
            ["General_UpToDate"] = "您使用的是最新版本 (v{0})",
            ["General_UpdateAvailable"] = "发现新版本 (v{0})！",
            ["General_UpdateError"] = "检查更新失败，请检查网络连接。",
            ["General_SupportSection"] = "支持开发者",
            ["General_Support_Subtitle"] = "如果您喜欢 SanmiToys，欢迎支持我们的持续开发！",
            ["General_Support_JP_Title"] = "日语用户支持 (OFUSE)",
            ["General_Support_JP_Desc"] = "通过 OFUSE 发送支持留言或赞赏",
            ["General_Support_JP_Btn"] = "在 OFUSE 上支持",
            ["General_Support_Global_Title"] = "全球支持 (Buy Me a Coffee)",
            ["General_Support_Global_Desc"] = "通过 Buy Me a Coffee 请开发者喝杯咖啡",
            ["General_Support_Global_Btn"] = "Buy Me a Coffee",
            ["General_AboutSection"] = "关于",
            ["General_About_Author"] = "Created by sanmi / sanmiri",
            ["General_About_Framework"] = ".NET 8 / WPF-UI Fluent",

            ["Tray_OpenDashboard"] = "打开仪表板",
            ["Tray_Settings"] = "常规设置",
            ["Tray_Exit"] = "退出",

            ["Common_Settings"] = "设置",
            ["Common_Enabled"] = "已启用",
            ["Common_Disabled"] = "已禁用",
            ["Common_Clear"] = "清除",
            ["Common_Close"] = "关闭",
            ["Common_Copy"] = "复制",
            ["Common_Save"] = "保存",
            ["Common_Cancel"] = "取消",
            ["Common_Reset"] = "重置",
            ["Common_Add"] = "添加",
            ["Common_Delete"] = "删除",
            ["Common_Select"] = "选择",
            ["Common_NotSet"] = "未设置 (点击设置)",
            ["Common_PressKeys"] = "请按下按键...",

            ["FluidDrag_Name"] = "FluidDrag",
            ["FluidDrag_Desc"] = "点击窗口空白背景区域并拖动，随时随地自由移动窗口",
            ["FluidDrag_Subtitle"] = "点击窗口空白背景区域并拖动，随时随地自由移动窗口",
            ["FluidDrag_Enable_Desc"] = "在文本、按钮和链接等可交互区域优先进行正常操作，防止误拖拽。",
            ["FluidDrag_BehaviorSection"] = "拖动操作设置",
            ["FluidDrag_ModifierKey"] = "启用修饰键",
            ["FluidDrag_ModifierKey_Desc"] = "按住该键时启用拖动（选择“无”则常时有效）",
            ["FluidDrag_ResizeKey"] = "禁用修饰键",
            ["FluidDrag_ResizeKey_Desc"] = "按住该键时临时禁用拖动（例如选择文本时）",
            ["FluidDrag_Threshold"] = "拖动触发阈值",
            ["FluidDrag_Threshold_Desc"] = "防止点击抖动误触发的移动像素距离",
            ["FluidDrag_ExclusionsSection"] = "排除与限制",
            ["FluidDrag_ExcludeFullscreen"] = "全屏应用与游戏中自动禁用",
            ["FluidDrag_ExcludeFullscreen_Desc"] = "在游戏或全屏播放视频时自动禁用拖动",
            ["FluidDrag_ExcludeMaximized"] = "排除最大化窗口",
            ["FluidDrag_ExcludeMaximized_Desc"] = "处于最大化状态的窗口不进行拖动",
            ["FluidDrag_RunningAppsSection"] = "从运行中应用添加排除",
            ["FluidDrag_RunningApps_Title"] = "当前打开的窗口",
            ["FluidDrag_RunningApps_Desc"] = "一键将正在运行的程序添加到排除列表中",
            ["FluidDrag_RefreshAppsBtn"] = "刷新列表",
            ["FluidDrag_AddRunningAppBtn"] = "添加到排除",
            ["FluidDrag_ProcessListSection"] = "已排除进程列表",
            ["FluidDrag_AddProcess_Title"] = "手动添加进程名",
            ["FluidDrag_AddProcess_Desc"] = "排除特定可执行程序（例如: photoshop, blender, steam）",
            ["FluidDrag_AddProcess_Placeholder"] = "进程名 (例如: steam)",
            ["FluidDrag_TitleListSection"] = "排除窗口标题关键词",
            ["FluidDrag_AddTitle_Title"] = "手动添加标题关键词",
            ["FluidDrag_AddTitle_Desc"] = "排除窗口标题中包含指定文字的窗口",
            ["FluidDrag_AddTitle_Placeholder"] = "关键词 (例如: 预览)",
            ["FluidDrag_Mod_None"] = "无 (始终有效)",
            ["FluidDrag_Mod_NoneDisable"] = "无 (无禁用键)",
            ["FluidDrag_Mod_Alt"] = "Alt 键",
            ["FluidDrag_Mod_Win"] = "Win 键",
            ["FluidDrag_Mod_Ctrl"] = "Ctrl 键",
            ["FluidDrag_Mod_Shift"] = "Shift 键",

            ["FocusDimmer_Name"] = "FocusDimmer",
            ["FocusDimmer_Desc"] = "优雅暗化非活动窗口，提升专注度与沉浸感",
            ["FocusDimmer_Subtitle"] = "优雅暗化非活动窗口，提升专注度与沉浸感",
            ["FocusDimmer_Enable_Desc"] = "使视线集中在当前工作窗口，减少眩光和周围视觉干扰。",
            ["FocusDimmer_MultiMonitorSection"] = "多显示器设置",
            ["FocusDimmer_LinkMonitors"] = "所有显示器同步设置",
            ["FocusDimmer_LinkMonitors_Desc"] = "开启后所有屏幕应用相同的暗化设置",
            ["FocusDimmer_TargetMonitor"] = "目标显示器",
            ["FocusDimmer_TargetMonitor_Desc"] = "选择要单独设置的显示器",
            ["FocusDimmer_VisualSection"] = "暗化与色彩设置",
            ["FocusDimmer_DimOpacity"] = "暗化不透明度",
            ["FocusDimmer_DimOpacity_Desc"] = "背景窗口与桌面的暗化程度",
            ["FocusDimmer_DimColor"] = "遮罩颜色",
            ["FocusDimmer_DimColor_Desc"] = "暗化遮罩背景色（可选现代精选色板）",
            ["FocusDimmer_DimColor_Btn"] = "打开调色板",
            ["FocusDimmer_OptionsSection"] = "行为与排除选项",
            ["FocusDimmer_DimDesktopOnly"] = "仅暗化桌面",
            ["FocusDimmer_DimDesktopOnly_Desc"] = "保持所有应用窗口常亮，仅暗化壁纸与桌面图标",
            ["FocusDimmer_ExcludeTaskbar"] = "排除任务栏",
            ["FocusDimmer_ExcludeTaskbar_Desc"] = "保持任务栏始终高亮显示",
            ["FocusDimmer_ExcludeTopmost"] = "排除置顶窗口",
            ["FocusDimmer_ExcludeTopmost_Desc"] = "画中画或浮动小工具不进行暗化",
            ["FocusDimmer_IdleSection"] = "闲置暗化",
            ["FocusDimmer_IdleDim"] = "无操作时启用闲置暗化",
            ["FocusDimmer_IdleDim_Desc"] = "一段时间无鼠标键盘操作时进一步暗化屏幕",
            ["FocusDimmer_IdleTimeout"] = "闲置超时时间 (分钟)",
            ["FocusDimmer_IdleTimeout_Desc"] = "触发闲置暗化的无操作时间",
            ["FocusDimmer_IdleOpacity"] = "闲置暗化强度",
            ["FocusDimmer_IdleOpacity_Desc"] = "闲置时应用的遮罩不透明度",
            ["FocusDimmer_RulesSection"] = "进程规则",
            ["FocusDimmer_Inspector_Title"] = "窗口检查器",
            ["FocusDimmer_Inspector_Desc"] = "点击屏幕任意窗口以查看详细信息并自动添加规则",
            ["FocusDimmer_Inspector_Status"] = "左键点击固定列表 / Esc 退出",
            ["FocusDimmer_InspectorBtn"] = "启动检查器",
            ["FocusDimmer_AlwaysBright_Title"] = "常亮应用",
            ["FocusDimmer_AlwaysBright_Desc"] = "即使在后台也保持常亮的进程名（例如: obs64, discord）",
            ["FocusDimmer_AlwaysDark_Title"] = "常暗应用",
            ["FocusDimmer_AlwaysDark_Desc"] = "即使获得焦点也保持暗化的进程名",

            ["InspectorAction_Title"] = "添加规则",
            ["InspectorAction_Heading"] = "窗口操作",
            ["InspectorAction_AlwaysBright"] = "添加到常亮列表",
            ["InspectorAction_AlwaysDark"] = "添加到常暗列表",
            ["InspectorAction_CopyProcess"] = "复制进程名到剪贴板",
            ["ColorPicker_Title"] = "调色板",
            ["ColorPicker_Palette"] = "现代预设调色板",
            ["ColorPicker_CustomHex"] = "自定义 HEX 颜色代码",
            ["Color_Black"] = "纯黑 (#000000)",
            ["Color_Dark"] = "深灰 (#121212)",
            ["Color_Midnight"] = "午夜蓝 (#0B132B)",
            ["Color_Warm"] = "暖木炭 (#1C1917)",
            ["Color_Purple"] = "深紫 (#1E102F)",
            ["Color_Forest"] = "墨绿 (#064E3B)",
            ["Color_Blue"] = "藏青 (#1E3A8A)",

            ["SnapTrans_Name"] = "SnapTrans",
            ["SnapTrans_Desc"] = "框选屏幕区域快速 OCR 识别文字、实时翻译与朗读",
            ["SnapTrans_Subtitle"] = "框选屏幕区域快速 OCR 识别文字、实时翻译与朗读",
            ["SnapTrans_Enable_Desc"] = "通过快捷键快速截取图片、视频、游戏或网页上的文字并翻译。",
            ["SnapTrans_ShortcutSection"] = "快捷键设置",
            ["SnapTrans_CaptureHotkey"] = "截图快捷键",
            ["SnapTrans_CaptureHotkey_Desc"] = "点击输入框并按下快捷键（Ctrl, Alt, Shift, Win + 键）",
            ["SnapTrans_TranslationSection"] = "翻译引擎与语言设置",
            ["SnapTrans_Provider"] = "翻译服务商",
            ["SnapTrans_Provider_Desc"] = "选择使用的翻译服务（Google 免密钥版、DeepL、Gemini、OpenAI）",
            ["SnapTrans_TargetLang"] = "目标翻译语言",
            ["SnapTrans_TargetLang_Desc"] = "将提取文字翻译成的目标语言",
            ["SnapTrans_ApiSection"] = "API 密钥设置",
            ["SnapTrans_DeepLKey"] = "DeepL API 密钥",
            ["SnapTrans_DeepLKey_Desc"] = "DeepL API (Free / Pro) 认证密钥",
            ["SnapTrans_GeminiKey"] = "Gemini API 密钥",
            ["SnapTrans_GeminiKey_Desc"] = "从 Google AI Studio 获取的 API 密钥",
            ["SnapTrans_OpenAiKey"] = "OpenAI API 密钥",
            ["SnapTrans_OpenAiKey_Desc"] = "OpenAI Platform API 密钥",
            ["SnapTrans_BehaviorSection"] = "行为与剪贴板设置",
            ["SnapTrans_AutoCopy"] = "自动复制到剪贴板",
            ["SnapTrans_AutoCopy_Desc"] = "截图完成后自动将文本复制到剪贴板",
            ["SnapTrans_CopySource"] = "翻译前文本 (原文 / OCR)",
            ["SnapTrans_CopySource_Desc"] = "将 OCR 识别的原文复制到剪贴板",
            ["SnapTrans_CopyTranslated"] = "翻译后文本",
            ["SnapTrans_CopyTranslated_Desc"] = "将翻译后的文本复制到剪贴板",
            ["SnapTrans_AutoSpeak"] = "自动语音朗读",
            ["SnapTrans_AutoSpeak_Desc"] = "翻译完成后自动通过语音朗读译文",
            ["SnapTrans_TestSection"] = "测试",
            ["SnapTrans_Test_Title"] = "测试截图翻译",
            ["SnapTrans_Test_Desc"] = "在屏幕上选择一个区域进行实时测试",
            ["SnapTrans_Test_Btn"] = "开始区域选择",
            ["SnapTrans_ToolTip_Speak"] = "语音朗读",
            ["SnapTrans_ToolTip_CopyTrans"] = "复制译文",
            ["SnapTrans_ToolTip_Close"] = "关闭",
            ["SnapTrans_Snip_Hint"] = "拖动选择区域 | Esc 取消",

            ["SwiftVolume_Name"] = "SwiftVolume",
            ["SwiftVolume_Desc"] = "任务栏托盘图标、轻量混音器、滚轮调音与 HUD 显示",
            ["SwiftVolume_Subtitle"] = "任务栏托盘图标、轻量混音器、滚轮调音与 HUD 显示",
            ["SwiftVolume_Enable_Desc"] = "启用后在任务栏托盘显示独立图标，点击即可弹出轻量混音器。",
            ["SwiftVolume_ControlSection"] = "托盘与混音器行为",
            ["SwiftVolume_OpenAtCursor"] = "在光标位置打开混音器",
            ["SwiftVolume_OpenAtCursor_Desc"] = "点击托盘图标时，直接在鼠标光标上方弹出混音器",
            ["SwiftVolume_MiddleClickMute"] = "中键点击托盘图标静音",
            ["SwiftVolume_MiddleClickMute_Desc"] = "滚轮点击托盘扬声器或麦克风图标即时静音",
            ["SwiftVolume_HudSection"] = "HUD 屏幕提示设置",
            ["SwiftVolume_ShowHud"] = "显示音量 HUD",
            ["SwiftVolume_ShowHud_Desc"] = "调节音量时在屏幕上显示精美现代提示条",
            ["SwiftVolume_ShowDeviceSwitchHud"] = "切换音频设备时显示 HUD 通知",
            ["SwiftVolume_ShowDeviceSwitchHud_Desc"] = "默认扬声器或麦克风变更时在屏幕上提示设备名称",
            ["SwiftVolume_HudPosition"] = "HUD 显示位置",
            ["SwiftVolume_HudPosition_Desc"] = "选择 HUD 提示在屏幕上的位置",
            ["SwiftVolume_HudPos_Center"] = "屏幕中央",
            ["SwiftVolume_HudPos_TopCenter"] = "顶部居中",
            ["SwiftVolume_HudPos_BottomCenter"] = "底部居中",
            ["SwiftVolume_HudPos_TopLeft"] = "左上角",
            ["SwiftVolume_HudPos_TopRight"] = "右上角",
            ["SwiftVolume_HudPos_BottomLeft"] = "左下角",
            ["SwiftVolume_HudPos_BottomRight"] = "右下角",
            ["SwiftVolume_HudSize"] = "HUD 尺寸",
            ["SwiftVolume_HudSize_Desc"] = "屏幕 HUD 提示框的大小",
            ["SwiftVolume_HudSize_Small"] = "小",
            ["SwiftVolume_HudSize_Medium"] = "中",
            ["SwiftVolume_HudSize_Large"] = "大",
            ["SwiftVolume_HotkeysSection"] = "键盘快捷键",
            ["SwiftVolume_Hotkey_OpenMixer"] = "打开音量混音器",
            ["SwiftVolume_Hotkey_OpenMixer_Desc"] = "弹出轻量音量混音器的快捷键",
            ["SwiftVolume_Hotkey_Mute"] = "扬声器静音切换",
            ["SwiftVolume_Hotkey_Mute_Desc"] = "主音频静音 / 取消静音",
            ["SwiftVolume_Hotkey_MicMute"] = "麦克风静音切换",
            ["SwiftVolume_Hotkey_MicMute_Desc"] = "默认麦克风静音 / 取消静音",
            ["SwiftVolume_TestSection"] = "测试",
            ["SwiftVolume_TestMixer_Title"] = "测试音量混音器",
            ["SwiftVolume_TestMixer_Desc"] = "立即在屏幕上显示音量混音器界面",
            ["SwiftVolume_ShowMixerBtn"] = "显示混音器",
            ["SwiftVolume_Mixer_Tooltip_MuteSpeaker"] = "扬声器静音切换",
            ["SwiftVolume_Mixer_Tooltip_Expand"] = "展开/折叠全部设备",
            ["SwiftVolume_Mixer_Tooltip_MuteMic"] = "麦克风静音切换",
            ["SwiftVolume_Hud_SpeakerSwitch"] = "扬声器已切换",
            ["SwiftVolume_Hud_MicSwitch"] = "麦克风已切换",
            ["SwiftVolume_Hud_MicMuted"] = "麦克风已静音",
            ["SwiftVolume_Hud_MicUnmuted"] = "麦克风已取消静音",
            ["SwiftVolume_Tray_Speaker"] = "SwiftVolume 扬声器",
            ["SwiftVolume_Tray_Mic"] = "SwiftVolume 麦克风",
            ["SwiftVolume_Tray_OpenSettings"] = "SwiftVolume 设置"
        },

        ["zh-Hant"] = new Dictionary<string, string>
        {
            ["Nav_Dashboard"] = "儀表板",
            ["Nav_FluidDrag"] = "FluidDrag",
            ["Nav_FocusDimmer"] = "FocusDimmer",
            ["Nav_SnapTrans"] = "SnapTrans",
            ["Nav_SwiftVolume"] = "SwiftVolume",
            ["Nav_GeneralSettings"] = "一般設定",
            ["Nav_UpdateNow"] = "立即更新",
            ["Nav_UpdateVersion"] = "立即更新 (v{0})",
            ["Nav_UpdatingProgress"] = "更新中 {0}%",
            ["Nav_ApplyingUpdate"] = "正在套用更新...",
            ["Nav_UpdateNotificationTitle"] = "SanmiToys 更新",
            ["Nav_UpdateNotificationBody"] = "發現新版本 (v{0})。\n點擊查看更新。",

            ["Dashboard_Title"] = "SanmiToys",
            ["Dashboard_Subtitle"] = "讓桌面工作更直覺、流暢的模組化實用工具集",
            ["Dashboard_EnabledModules"] = "實用模組清單",
            ["Dashboard_SettingsBtn"] = "設定",

            ["General_Title"] = "一般設定",
            ["General_Subtitle"] = "SanmiToys 啟動行為與系統整合設定",
            ["General_LanguageSection"] = "語言設定",
            ["General_Language_Title"] = "顯示語言",
            ["General_Language_Desc"] = "變更應用程式的顯示語言",
            ["General_StartupSection"] = "啟動與行為",
            ["General_Startup_Title"] = "開機自動啟動",
            ["General_Startup_Desc"] = "在 Windows 啟動時自動於背景執行",
            ["General_MinimizeToTray_Title"] = "點擊關閉（×）最小化至系統匣",
            ["General_MinimizeToTray_Desc"] = "關閉視窗後工具仍在背景保持運作",
            ["General_UpdatesSection"] = "軟體更新",
            ["General_Updates_Title"] = "檢查更新",
            ["General_Updates_Desc"] = "檢查最新功能與錯誤修正",
            ["General_CheckUpdatesBtn"] = "檢查更新",
            ["General_CheckingUpdates"] = "正在檢查更新...",
            ["General_ApplyUpdateBtn"] = "立即更新並重啟",
            ["General_UpdatingMessage"] = "正在下載更新... ({0}%)",
            ["General_UpToDate"] = "您使用的是最新版本 (v{0})",
            ["General_UpdateAvailable"] = "發現新版本 (v{0})！",
            ["General_UpdateError"] = "檢查更新失敗，請檢查網路連線。",
            ["General_SupportSection"] = "支持開發者",
            ["General_Support_Subtitle"] = "如果您喜歡 SanmiToys，歡迎贊助支持持續開發！",
            ["General_Support_JP_Title"] = "日語用戶支援 (OFUSE)",
            ["General_Support_JP_Desc"] = "透過 OFUSE 發送支持留言或贊助",
            ["General_Support_JP_Btn"] = "在 OFUSE 上贊助",
            ["General_Support_Global_Title"] = "全球支援 (Buy Me a Coffee)",
            ["General_Support_Global_Desc"] = "透過 Buy Me a Coffee 請開發者喝杯咖啡",
            ["General_Support_Global_Btn"] = "Buy Me a Coffee",
            ["General_AboutSection"] = "關於",
            ["General_About_Author"] = "Created by sanmi / sanmiri",
            ["General_About_Framework"] = ".NET 8 / WPF-UI Fluent",

            ["Tray_OpenDashboard"] = "開啟儀表板",
            ["Tray_Settings"] = "一般設定",
            ["Tray_Exit"] = "結束",

            ["Common_Settings"] = "設定",
            ["Common_Enabled"] = "已啟用",
            ["Common_Disabled"] = "已停用",
            ["Common_Clear"] = "清除",
            ["Common_Close"] = "關閉",
            ["Common_Copy"] = "複製",
            ["Common_Save"] = "儲存",
            ["Common_Cancel"] = "取消",
            ["Common_Reset"] = "重設",
            ["Common_Add"] = "新增",
            ["Common_Delete"] = "刪除",
            ["Common_Select"] = "選擇",
            ["Common_NotSet"] = "未設定 (點擊設定)",
            ["Common_PressKeys"] = "請按下按鍵...",

            ["FluidDrag_Name"] = "FluidDrag",
            ["FluidDrag_Desc"] = "點擊視窗空白背景區域並拖曳，隨時隨地自由移動視窗",
            ["FluidDrag_Subtitle"] = "點擊視窗空白背景區域並拖曳，隨時隨地自由移動視窗",
            ["FluidDrag_Enable_Desc"] = "在文字、按鈕和連結等可操作區域優先進行正常操作，防止誤拖曳。",
            ["FluidDrag_BehaviorSection"] = "拖曳操作設定",
            ["FluidDrag_ModifierKey"] = "啟用輔助鍵",
            ["FluidDrag_ModifierKey_Desc"] = "按住該鍵時啟用拖曳（選擇「無」則常時有效）",
            ["FluidDrag_ResizeKey"] = "停用輔助鍵",
            ["FluidDrag_ResizeKey_Desc"] = "按住該鍵時暫時停用拖曳（例如選取文字時）",
            ["FluidDrag_Threshold"] = "拖曳觸發臨界值",
            ["FluidDrag_Threshold_Desc"] = "防止點擊抖動誤觸發的移動像素距離",
            ["FluidDrag_ExclusionsSection"] = "排除與限制",
            ["FluidDrag_ExcludeFullscreen"] = "全螢幕應用與遊戲中自動停用",
            ["FluidDrag_ExcludeFullscreen_Desc"] = "在遊戲或全螢幕播放影片時自動停用拖曳",
            ["FluidDrag_ExcludeMaximized"] = "排除最大化視窗",
            ["FluidDrag_ExcludeMaximized_Desc"] = "處於最大化狀態的視窗不進行拖曳",
            ["FluidDrag_RunningAppsSection"] = "從執行中應用新增排除",
            ["FluidDrag_RunningApps_Title"] = "目前開啟的視窗",
            ["FluidDrag_RunningApps_Desc"] = "一鍵將正在執行的程式新增至排除清單中",
            ["FluidDrag_RefreshAppsBtn"] = "重新整理清單",
            ["FluidDrag_AddRunningAppBtn"] = "新增至排除",
            ["FluidDrag_ProcessListSection"] = "已排除處理程序清單",
            ["FluidDrag_AddProcess_Title"] = "手動新增處理程序名稱",
            ["FluidDrag_AddProcess_Desc"] = "排除特定執行檔（例如: photoshop, blender, steam）",
            ["FluidDrag_AddProcess_Placeholder"] = "處理程序名稱 (例如: steam)",
            ["FluidDrag_TitleListSection"] = "排除視窗標題關鍵字",
            ["FluidDrag_AddTitle_Title"] = "手動新增標題關鍵字",
            ["FluidDrag_AddTitle_Desc"] = "排除視窗標題中包含指定文字的視窗",
            ["FluidDrag_AddTitle_Placeholder"] = "關鍵字 (例如: 預覽)",
            ["FluidDrag_Mod_None"] = "無 (始終有效)",
            ["FluidDrag_Mod_NoneDisable"] = "無 (無停用鍵)",
            ["FluidDrag_Mod_Alt"] = "Alt 鍵",
            ["FluidDrag_Mod_Win"] = "Win 鍵",
            ["FluidDrag_Mod_Ctrl"] = "Ctrl 鍵",
            ["FluidDrag_Mod_Shift"] = "Shift 鍵",

            ["FocusDimmer_Name"] = "FocusDimmer",
            ["FocusDimmer_Desc"] = "優雅暗化非使用中視窗，提升專注度與沉浸感",
            ["FocusDimmer_Subtitle"] = "優雅暗化非使用中視窗，提升專注度與沉浸感",
            ["FocusDimmer_Enable_Desc"] = "使視線集中在當前工作視窗，減少眩光和周圍視覺干擾。",
            ["FocusDimmer_MultiMonitorSection"] = "多顯示器設定",
            ["FocusDimmer_LinkMonitors"] = "所有顯示器同步設定",
            ["FocusDimmer_LinkMonitors_Desc"] = "開啟後所有螢幕套用相同的暗化設定",
            ["FocusDimmer_TargetMonitor"] = "目標顯示器",
            ["FocusDimmer_TargetMonitor_Desc"] = "選擇要個別設定的顯示器",
            ["FocusDimmer_VisualSection"] = "暗化與色彩設定",
            ["FocusDimmer_DimOpacity"] = "暗化不透明度",
            ["FocusDimmer_DimOpacity_Desc"] = "背景視窗與桌面的暗化程度",
            ["FocusDimmer_DimColor"] = "遮罩顏色",
            ["FocusDimmer_DimColor_Desc"] = "暗化遮罩背景色（可選現代精選色盤）",
            ["FocusDimmer_DimColor_Btn"] = "開啟調色盤",
            ["FocusDimmer_OptionsSection"] = "行為與排除選項",
            ["FocusDimmer_DimDesktopOnly"] = "僅暗化桌面",
            ["FocusDimmer_DimDesktopOnly_Desc"] = "保持所有應用程式視窗常亮，僅暗化桌布與桌面圖示",
            ["FocusDimmer_ExcludeTaskbar"] = "排除工作列",
            ["FocusDimmer_ExcludeTaskbar_Desc"] = "保持工作列始終高亮顯示",
            ["FocusDimmer_ExcludeTopmost"] = "排除最上層視窗",
            ["FocusDimmer_ExcludeTopmost_Desc"] = "子母畫面或浮動小工具不進行暗化",
            ["FocusDimmer_IdleSection"] = "閒置暗化",
            ["FocusDimmer_IdleDim"] = "無操作時啟用閒置暗化",
            ["FocusDimmer_IdleDim_Desc"] = "一段時間無滑鼠鍵盤操作時進一步暗化螢幕",
            ["FocusDimmer_IdleTimeout"] = "閒置逾時時間 (分鐘)",
            ["FocusDimmer_IdleTimeout_Desc"] = "觸發閒置暗化的無操作時間",
            ["FocusDimmer_IdleOpacity"] = "閒置暗化強度",
            ["FocusDimmer_IdleOpacity_Desc"] = "閒置時套用的遮罩不透明度",
            ["FocusDimmer_RulesSection"] = "處理程序規則",
            ["FocusDimmer_Inspector_Title"] = "視窗檢查器",
            ["FocusDimmer_Inspector_Desc"] = "點擊螢幕任意視窗以查看詳細資訊並自動新增規則",
            ["FocusDimmer_Inspector_Status"] = "左鍵點擊固定清單 / Esc 結束",
            ["FocusDimmer_InspectorBtn"] = "啟動檢查器",
            ["FocusDimmer_AlwaysBright_Title"] = "常亮應用程式",
            ["FocusDimmer_AlwaysBright_Desc"] = "即使在背景也保持常亮的處理程序名稱（例如: obs64, discord）",
            ["FocusDimmer_AlwaysDark_Title"] = "常暗應用程式",
            ["FocusDimmer_AlwaysDark_Desc"] = "即使獲得焦點也保持暗化的處理程序名稱",

            ["InspectorAction_Title"] = "新增規則",
            ["InspectorAction_Heading"] = "視窗操作",
            ["InspectorAction_AlwaysBright"] = "新增至常亮清單",
            ["InspectorAction_AlwaysDark"] = "新增至常暗清單",
            ["InspectorAction_CopyProcess"] = "複製處理程序名稱至剪貼簿",
            ["ColorPicker_Title"] = "調色盤",
            ["ColorPicker_Palette"] = "現代預設調色盤",
            ["ColorPicker_CustomHex"] = "自訂 HEX 顏色代碼",
            ["Color_Black"] = "純黑 (#000000)",
            ["Color_Dark"] = "深灰 (#121212)",
            ["Color_Midnight"] = "午夜藍 (#0B132B)",
            ["Color_Warm"] = "暖木炭 (#1C1917)",
            ["Color_Purple"] = "深紫 (#1E102F)",
            ["Color_Forest"] = "墨綠 (#064E3B)",
            ["Color_Blue"] = "海軍藍 (#1E3A8A)",

            ["SnapTrans_Name"] = "SnapTrans",
            ["SnapTrans_Desc"] = "框選螢幕區域快速 OCR 辨識文字、即時翻譯與朗讀",
            ["SnapTrans_Subtitle"] = "框選螢幕區域快速 OCR 辨識文字、即時翻譯與朗讀",
            ["SnapTrans_Enable_Desc"] = "透過快捷鍵快速擷取圖片、影片、遊戲或網頁上的文字並翻譯。",
            ["SnapTrans_ShortcutSection"] = "快捷鍵設定",
            ["SnapTrans_CaptureHotkey"] = "截圖快捷鍵",
            ["SnapTrans_CaptureHotkey_Desc"] = "點擊輸入框並按下快捷鍵（Ctrl, Alt, Shift, Win + 鍵）",
            ["SnapTrans_TranslationSection"] = "翻譯引擎與語言設定",
            ["SnapTrans_Provider"] = "翻譯服務商",
            ["SnapTrans_Provider_Desc"] = "選擇使用的翻譯服務（Google 免金鑰版、DeepL、Gemini、OpenAI）",
            ["SnapTrans_TargetLang"] = "目標翻譯語言",
            ["SnapTrans_TargetLang_Desc"] = "將擷取文字翻譯成的目標語言",
            ["SnapTrans_ApiSection"] = "API 金鑰設定",
            ["SnapTrans_DeepLKey"] = "DeepL API 金鑰",
            ["SnapTrans_DeepLKey_Desc"] = "DeepL API (Free / Pro) 認證金鑰",
            ["SnapTrans_GeminiKey"] = "Gemini API 金鑰",
            ["SnapTrans_GeminiKey_Desc"] = "從 Google AI Studio 取得的 API 金鑰",
            ["SnapTrans_OpenAiKey"] = "OpenAI API 金鑰",
            ["SnapTrans_OpenAiKey_Desc"] = "OpenAI Platform API 金鑰",
            ["SnapTrans_BehaviorSection"] = "行為與剪貼簿設定",
            ["SnapTrans_AutoCopy"] = "自動複製至剪貼簿",
            ["SnapTrans_AutoCopy_Desc"] = "截圖完成後自動將文字複製至剪貼簿",
            ["SnapTrans_CopySource"] = "翻譯前文字 (原文 / OCR)",
            ["SnapTrans_CopySource_Desc"] = "將 OCR 辨識的原文複製至剪貼簿",
            ["SnapTrans_CopyTranslated"] = "翻譯後文字",
            ["SnapTrans_CopyTranslated_Desc"] = "將翻譯後的文字複製至剪貼簿",
            ["SnapTrans_AutoSpeak"] = "自動語音朗讀",
            ["SnapTrans_AutoSpeak_Desc"] = "翻譯完成後自動透過語音朗讀譯文",
            ["SnapTrans_TestSection"] = "測試",
            ["SnapTrans_Test_Title"] = "測試截圖翻譯",
            ["SnapTrans_Test_Desc"] = "在螢幕上選擇一個區域進行即時測試",
            ["SnapTrans_Test_Btn"] = "開始區域選取",
            ["SnapTrans_ToolTip_Speak"] = "語音朗讀",
            ["SnapTrans_ToolTip_CopyTrans"] = "複製譯文",
            ["SnapTrans_ToolTip_Close"] = "關閉",
            ["SnapTrans_Snip_Hint"] = "拖曳選擇區域 | Esc 取消",

            ["SwiftVolume_Name"] = "SwiftVolume",
            ["SwiftVolume_Desc"] = "工作列系統匣圖示、輕量混音程式、滾輪調音與 HUD 顯示",
            ["SwiftVolume_Subtitle"] = "工作列系統匣圖示、輕量混音程式、滾輪調音與 HUD 顯示",
            ["SwiftVolume_Enable_Desc"] = "啟用後在工作列系統匣顯示獨立圖示，點擊即可彈出輕量混音程式。",
            ["SwiftVolume_ControlSection"] = "系統匣與混音程式行為",
            ["SwiftVolume_OpenAtCursor"] = "在游標位置開啟混音程式",
            ["SwiftVolume_OpenAtCursor_Desc"] = "點擊系統匣圖示時，直接在滑鼠游標上方彈出混音程式",
            ["SwiftVolume_MiddleClickMute"] = "中鍵點擊系統匣圖示靜音",
            ["SwiftVolume_MiddleClickMute_Desc"] = "滾輪點擊系統匣喇叭或麥克風圖示即時靜音",
            ["SwiftVolume_HudSection"] = "HUD 螢幕提示設定",
            ["SwiftVolume_ShowHud"] = "顯示音量 HUD",
            ["SwiftVolume_ShowHud_Desc"] = "調整音量時在螢幕上顯示精美現代提示條",
            ["SwiftVolume_ShowDeviceSwitchHud"] = "切換音訊裝置時顯示 HUD 通知",
            ["SwiftVolume_ShowDeviceSwitchHud_Desc"] = "預設喇叭或麥克風變更時在螢幕上提示裝置名稱",
            ["SwiftVolume_HudPosition"] = "HUD 顯示位置",
            ["SwiftVolume_HudPosition_Desc"] = "選擇 HUD 提示在螢幕上的位置",
            ["SwiftVolume_HudPos_Center"] = "螢幕中央",
            ["SwiftVolume_HudPos_TopCenter"] = "頂部置中",
            ["SwiftVolume_HudPos_BottomCenter"] = "底部置中",
            ["SwiftVolume_HudPos_TopLeft"] = "左上角",
            ["SwiftVolume_HudPos_TopRight"] = "右上角",
            ["SwiftVolume_HudPos_BottomLeft"] = "左下角",
            ["SwiftVolume_HudPos_BottomRight"] = "右下角",
            ["SwiftVolume_HudSize"] = "HUD 尺寸",
            ["SwiftVolume_HudSize_Desc"] = "螢幕 HUD 提示框的大小",
            ["SwiftVolume_HudSize_Small"] = "小",
            ["SwiftVolume_HudSize_Medium"] = "中",
            ["SwiftVolume_HudSize_Large"] = "大",
            ["SwiftVolume_HotkeysSection"] = "鍵盤快捷鍵",
            ["SwiftVolume_Hotkey_OpenMixer"] = "開啟音量混音程式",
            ["SwiftVolume_Hotkey_OpenMixer_Desc"] = "彈出輕量音量混音程式的快捷鍵",
            ["SwiftVolume_Hotkey_Mute"] = "喇叭靜音切換",
            ["SwiftVolume_Hotkey_Mute_Desc"] = "主要音訊靜音 / 取消靜音",
            ["SwiftVolume_Hotkey_MicMute"] = "麥克風靜音切換",
            ["SwiftVolume_Hotkey_MicMute_Desc"] = "預設麥克風靜音 / 取消靜音",
            ["SwiftVolume_TestSection"] = "測試",
            ["SwiftVolume_TestMixer_Title"] = "測試音量混音程式",
            ["SwiftVolume_TestMixer_Desc"] = "立即在螢幕上顯示音量混音程式介面",
            ["SwiftVolume_ShowMixerBtn"] = "顯示混音程式",
            ["SwiftVolume_Mixer_Tooltip_MuteSpeaker"] = "喇叭靜音切換",
            ["SwiftVolume_Mixer_Tooltip_Expand"] = "展開/摺疊全部裝置",
            ["SwiftVolume_Mixer_Tooltip_MuteMic"] = "麥克風靜音切換",
            ["SwiftVolume_Hud_SpeakerSwitch"] = "喇叭已切換",
            ["SwiftVolume_Hud_MicSwitch"] = "麥克風已切換",
            ["SwiftVolume_Hud_MicMuted"] = "麥克風已靜音",
            ["SwiftVolume_Hud_MicUnmuted"] = "麥克風已取消靜音",
            ["SwiftVolume_Tray_Speaker"] = "SwiftVolume 喇叭",
            ["SwiftVolume_Tray_Mic"] = "SwiftVolume 麥克風",
            ["SwiftVolume_Tray_OpenSettings"] = "SwiftVolume 設定"
        },

        ["ko"] = new Dictionary<string, string>
        {
            ["Nav_Dashboard"] = "대시보드",
            ["Nav_FluidDrag"] = "FluidDrag",
            ["Nav_FocusDimmer"] = "FocusDimmer",
            ["Nav_SnapTrans"] = "SnapTrans",
            ["Nav_SwiftVolume"] = "SwiftVolume",
            ["Nav_GeneralSettings"] = "일반 설정",
            ["Nav_UpdateNow"] = "지금 업데이트",
            ["Nav_UpdateVersion"] = "지금 업데이트 (v{0})",
            ["Nav_UpdatingProgress"] = "업데이트 중 {0}%",
            ["Nav_ApplyingUpdate"] = "업데이트 적용 중...",
            ["Nav_UpdateNotificationTitle"] = "SanmiToys 업데이트",
            ["Nav_UpdateNotificationBody"] = "새 버전 (v{0})을 사용할 수 있습니다.\n클릭하여 업데이트를 확인하세요.",

            ["Dashboard_Title"] = "SanmiToys",
            ["Dashboard_Subtitle"] = "직관적이고 스마트한 데스크톱 작업을 위한 모듈형 유틸리티 스위트",
            ["Dashboard_EnabledModules"] = "활성 유틸리티 모듈",
            ["Dashboard_SettingsBtn"] = "설정",

            ["General_Title"] = "일반 설정",
            ["General_Subtitle"] = "SanmiToys 시작 동작 및 시스템 통합 설정",
            ["General_LanguageSection"] = "언어 설정",
            ["General_Language_Title"] = "표시 언어",
            ["General_Language_Desc"] = "애플리케이션 표시 언어를 변경합니다",
            ["General_StartupSection"] = "시작 및 동작",
            ["General_Startup_Title"] = "Windows 시작 시 자동 실행",
            ["General_Startup_Desc"] = "PC 부팅 시 백그라운드에서 자동으로 시작합니다",
            ["General_MinimizeToTray_Title"] = "닫기 버튼(×) 클릭 시 시스템 트레이로 최소화",
            ["General_MinimizeToTray_Desc"] = "창을 닫아도 도구가 백그라운드에서 계속 실행됩니다",
            ["General_UpdatesSection"] = "업데이트",
            ["General_Updates_Title"] = "업데이트 확인",
            ["General_Updates_Desc"] = "최신 기능 및 수정 사항을 확인합니다",
            ["General_CheckUpdatesBtn"] = "업데이트 확인",
            ["General_CheckingUpdates"] = "업데이트 확인 중...",
            ["General_ApplyUpdateBtn"] = "지금 업데이트 및 재시작",
            ["General_UpdatingMessage"] = "업데이트 다운로드 중... ({0}%)",
            ["General_UpToDate"] = "최신 버전을 사용 중입니다 (v{0})",
            ["General_UpdateAvailable"] = "새 버전 (v{0})을 사용할 수 있습니다!",
            ["General_UpdateError"] = "업데이트 확인 실패. 네트워크 연결을 확인하세요.",
            ["General_SupportSection"] = "개발자 후원",
            ["General_Support_Subtitle"] = "SanmiToys가 유용하셨다면 지속적인 개발을 위해 후원해 주세요!",
            ["General_Support_JP_Title"] = "일본어 사용자 지원 (OFUSE)",
            ["General_Support_JP_Desc"] = "OFUSE를 통해 응원 메시지와 함께 후원할 수 있습니다",
            ["General_Support_JP_Btn"] = "OFUSE로 후원하기",
            ["General_Support_Global_Title"] = "해외 후원 (Buy Me a Coffee)",
            ["General_Support_Global_Desc"] = "Buy Me a Coffee에서 커피 한 잔으로 가볍게 후원할 수 있습니다",
            ["General_Support_Global_Btn"] = "Buy Me a Coffee",
            ["General_AboutSection"] = "정보",
            ["General_About_Author"] = "Created by sanmi / sanmiri",
            ["General_About_Framework"] = ".NET 8 / WPF-UI Fluent",

            ["Tray_OpenDashboard"] = "대시보드 열기",
            ["Tray_Settings"] = "일반 설정",
            ["Tray_Exit"] = "종료",

            ["Common_Settings"] = "설정",
            ["Common_Enabled"] = "활성화됨",
            ["Common_Disabled"] = "비활성화됨",
            ["Common_Clear"] = "지우기",
            ["Common_Close"] = "닫기",
            ["Common_Copy"] = "복사",
            ["Common_Save"] = "저장",
            ["Common_Cancel"] = "취소",
            ["Common_Reset"] = "초기화",
            ["Common_Add"] = "추가",
            ["Common_Delete"] = "삭제",
            ["Common_Select"] = "선택",
            ["Common_NotSet"] = "미설정 (클릭하여 입력)",
            ["Common_PressKeys"] = "키를 눌러주세요...",

            ["FluidDrag_Name"] = "FluidDrag",
            ["FluidDrag_Desc"] = "창의 빈 배경 영역을 클릭하고 드래그하여 자유롭게 창 이동",
            ["FluidDrag_Subtitle"] = "창의 빈 배경 영역을 클릭하고 드래그하여 자유롭게 창 이동",
            ["FluidDrag_Enable_Desc"] = "텍스트, 버튼, 링크 등 조작 가능 영역에서는 정상 조작이 우선 적용되어 오작동을 방지합니다.",
            ["FluidDrag_BehaviorSection"] = "드래그 동작 설정",
            ["FluidDrag_ModifierKey"] = "활성화 키",
            ["FluidDrag_ModifierKey_Desc"] = "누르고 있는 동안 드래그 이동 활성화 ('없음' 선택 시 항상 활성)",
            ["FluidDrag_ResizeKey"] = "비활성화 키",
            ["FluidDrag_ResizeKey_Desc"] = "누르고 있는 동안 드래그 이동을 일시 비활성화 (텍스트 선택 등)",
            ["FluidDrag_Threshold"] = "드래그 시작 이동 임계값",
            ["FluidDrag_Threshold_Desc"] = "클릭 흔들림으로 인한 오작동 방지 픽셀 거리",
            ["FluidDrag_ExclusionsSection"] = "동작 제외 및 제한",
            ["FluidDrag_ExcludeFullscreen"] = "전체화면 앱 및 게임에서 자동 제외",
            ["FluidDrag_ExcludeFullscreen_Desc"] = "게임 플레이나 전체화면 동영상 재생 시 드래그 완전 비활성화",
            ["FluidDrag_ExcludeMaximized"] = "최대화된 창 제외",
            ["FluidDrag_ExcludeMaximized_Desc"] = "최대화된 창은 드래그 이동 대상에서 제외",
            ["FluidDrag_RunningAppsSection"] = "실행 중인 앱에서 제외 추가",
            ["FluidDrag_RunningApps_Title"] = "현재 열려있는 창 목록",
            ["FluidDrag_RunningApps_Desc"] = "실행 중인 앱 목록에서 원클릭으로 제외 목록에 추가",
            ["FluidDrag_RefreshAppsBtn"] = "목록 새로고침",
            ["FluidDrag_AddRunningAppBtn"] = "제외 목록에 추가",
            ["FluidDrag_ProcessListSection"] = "제외된 프로세스 목록",
            ["FluidDrag_AddProcess_Title"] = "프로세스명 수동 추가",
            ["FluidDrag_AddProcess_Desc"] = "특정 실행 파일명 (예: photoshop, blender, steam) 제외 등록",
            ["FluidDrag_AddProcess_Placeholder"] = "프로세스명 (예: steam)",
            ["FluidDrag_TitleListSection"] = "제외 창 제목 키워드",
            ["FluidDrag_AddTitle_Title"] = "제목 키워드 수동 추가",
            ["FluidDrag_AddTitle_Desc"] = "창 제목에 지정된 문구가 포함된 경우 제외",
            ["FluidDrag_AddTitle_Placeholder"] = "키워드 (예: 미리보기)",
            ["FluidDrag_Mod_None"] = "없음 (항상 활성)",
            ["FluidDrag_Mod_NoneDisable"] = "없음 (비활성화 키 없음)",
            ["FluidDrag_Mod_Alt"] = "Alt 키",
            ["FluidDrag_Mod_Win"] = "Win 키",
            ["FluidDrag_Mod_Ctrl"] = "Ctrl 키",
            ["FluidDrag_Mod_Shift"] = "Shift 키",

            ["FocusDimmer_Name"] = "FocusDimmer",
            ["FocusDimmer_Desc"] = "활성 창 외의 배경을 어둡게 하여 몰입감과 집중력을 극대화",
            ["FocusDimmer_Subtitle"] = "활성 창 외의 배경을 어둡게 하여 몰입감과 집중력을 극대화",
            ["FocusDimmer_Enable_Desc"] = "작업 중인 창에 시선을 집중시키고 화면 눈부심과 주변 시각 노이즈를 줄입니다.",
            ["FocusDimmer_MultiMonitorSection"] = "다중 모니터 설정",
            ["FocusDimmer_LinkMonitors"] = "모든 모니터 설정 연동",
            ["FocusDimmer_LinkMonitors_Desc"] = "켜면 모든 모니터에 동일한 감광 설정이 적용됩니다",
            ["FocusDimmer_TargetMonitor"] = "설정 대상 모니터",
            ["FocusDimmer_TargetMonitor_Desc"] = "개별 설정을 진행할 모니터를 선택하세요",
            ["FocusDimmer_VisualSection"] = "감광 및 색상 설정",
            ["FocusDimmer_DimOpacity"] = "감광률 (불투명도)",
            ["FocusDimmer_DimOpacity_Desc"] = "배경 창 및 데스크톱을 어둡게 할 강도",
            ["FocusDimmer_DimColor"] = "오버레이 색상",
            ["FocusDimmer_DimColor_Desc"] = "감광 오버레이 색상 (모던 팔레트에서 선택 가능)",
            ["FocusDimmer_DimColor_Btn"] = "색상 팔레트 열기",
            ["FocusDimmer_OptionsSection"] = "동작 및 제외 옵션",
            ["FocusDimmer_DimDesktopOnly"] = "바탕화면만 감광",
            ["FocusDimmer_DimDesktopOnly_Desc"] = "다른 모든 앱 창은 밝게 유지하고 배경화면과 아이콘만 어둡게 합니다",
            ["FocusDimmer_ExcludeTaskbar"] = "작업 표시줄 제외",
            ["FocusDimmer_ExcludeTaskbar_Desc"] = "작업 표시줄은 감광하지 않고 항상 밝게 유지",
            ["FocusDimmer_ExcludeTopmost"] = "항상 위 창 제외",
            ["FocusDimmer_ExcludeTopmost_Desc"] = "PiP 플레이어나 플로팅 도구는 감광에서 제외",
            ["FocusDimmer_IdleSection"] = "유휴 감광",
            ["FocusDimmer_IdleDim"] = "미조작 시 유휴 감광 활성화",
            ["FocusDimmer_IdleDim_Desc"] = "일정 시간 마우스/키보드 조작이 없을 시 화면 전체를 추가 감광",
            ["FocusDimmer_IdleTimeout"] = "유휴 판정 시간 (분)",
            ["FocusDimmer_IdleTimeout_Desc"] = "감광을 시작할 때까지의 대기 시간 (분)",
            ["FocusDimmer_IdleOpacity"] = "유휴 감광 강도",
            ["FocusDimmer_IdleOpacity_Desc"] = "유휴 상태 시 적용할 강한 감광 불투명도",
            ["FocusDimmer_RulesSection"] = "프로세스별 규칙",
            ["FocusDimmer_Inspector_Title"] = "창 인스펙터",
            ["FocusDimmer_Inspector_Desc"] = "화면의 아무 창이나 클릭하여 프로세스 정보를 조사하고 자동 등록",
            ["FocusDimmer_Inspector_Status"] = "좌클릭으로 목록 고정 / Esc로 종료",
            ["FocusDimmer_InspectorBtn"] = "인스펙터 실행",
            ["FocusDimmer_AlwaysBright_Title"] = "항상 밝게 유지할 앱",
            ["FocusDimmer_AlwaysBright_Desc"] = "백그라운드에 있어도 감광하지 않을 프로세스명 (예: obs64, discord)",
            ["FocusDimmer_AlwaysDark_Title"] = "항상 감광할 앱",
            ["FocusDimmer_AlwaysDark_Desc"] = "포커스를 받아도 감광을 유지할 프로세스명",

            ["InspectorAction_Title"] = "규칙 추가",
            ["InspectorAction_Heading"] = "창 동작",
            ["InspectorAction_AlwaysBright"] = "항상 밝은 목록에 추가",
            ["InspectorAction_AlwaysDark"] = "항상 감광 목록에 추가",
            ["InspectorAction_CopyProcess"] = "프로세스명을 클립보드에 복사",
            ["ColorPicker_Title"] = "색상 팔레트",
            ["ColorPicker_Palette"] = "모던 프리셋 팔레트",
            ["ColorPicker_CustomHex"] = "커스텀 HEX 색상 코드",
            ["Color_Black"] = "퓨어 블랙 (#000000)",
            ["Color_Dark"] = "다크 슬레이트 (#121212)",
            ["Color_Midnight"] = "미드나잇 블루 (#0B132B)",
            ["Color_Warm"] = "웜 차콜 (#1C1917)",
            ["Color_Purple"] = "딥 퍼플 (#1E102F)",
            ["Color_Forest"] = "포레스트 다크 (#064E3B)",
            ["Color_Blue"] = "네이비 블루 (#1E3A8A)",

            ["SnapTrans_Name"] = "SnapTrans",
            ["SnapTrans_Desc"] = "화면 영역을 캡처하여 즉시 OCR 문자 인식, 번역 및 음성 읽기",
            ["SnapTrans_Subtitle"] = "화면 영역을 캡처하여 즉시 OCR 문자 인식, 번역 및 음성 읽기",
            ["SnapTrans_Enable_Desc"] = "단축키로 이미지, 게임, 웹 화면의 텍스트를 영역 선택하여 즉시 번역합니다.",
            ["SnapTrans_ShortcutSection"] = "단축키 설정",
            ["SnapTrans_CaptureHotkey"] = "캡처 시작 핫키",
            ["SnapTrans_CaptureHotkey_Desc"] = "상자를 클릭하고 원하는 단축키(Ctrl, Alt, Shift, Win + 키)를 누르면 등록됩니다",
            ["SnapTrans_TranslationSection"] = "번역 엔진 및 언어 설정",
            ["SnapTrans_Provider"] = "번역 공급자",
            ["SnapTrans_Provider_Desc"] = "사용할 번역 서비스 (Google 웹 무료, DeepL, Gemini, OpenAI) 선택",
            ["SnapTrans_TargetLang"] = "번역 대상 언어",
            ["SnapTrans_TargetLang_Desc"] = "추출된 텍스트를 번역할 언어",
            ["SnapTrans_ApiSection"] = "API 키 설정",
            ["SnapTrans_DeepLKey"] = "DeepL API 키",
            ["SnapTrans_DeepLKey_Desc"] = "DeepL API (Free / Pro) 인증 키",
            ["SnapTrans_GeminiKey"] = "Gemini API 키",
            ["SnapTrans_GeminiKey_Desc"] = "Google AI Studio에서 발급받은 API 키",
            ["SnapTrans_OpenAiKey"] = "OpenAI API 키",
            ["SnapTrans_OpenAiKey_Desc"] = "OpenAI Platform API 키",
            ["SnapTrans_BehaviorSection"] = "동작 및 클립보드 설정",
            ["SnapTrans_AutoCopy"] = "클립보드에 자동 복사",
            ["SnapTrans_AutoCopy_Desc"] = "캡처 완료 시 텍스트를 클립보드에 자동으로 복사합니다",
            ["SnapTrans_CopySource"] = "번역 전 텍스트 (원문 / OCR)",
            ["SnapTrans_CopySource_Desc"] = "OCR로 인식된 원문 텍스트를 복사합니다",
            ["SnapTrans_CopyTranslated"] = "번역 후 텍스트",
            ["SnapTrans_CopyTranslated_Desc"] = "번역 완료된 텍스트를 복사합니다",
            ["SnapTrans_AutoSpeak"] = "자동 음성 읽기",
            ["SnapTrans_AutoSpeak_Desc"] = "번역 완료 즉시 음성으로 읽어줍니다",
            ["SnapTrans_TestSection"] = "테스트 실행",
            ["SnapTrans_Test_Title"] = "지금 캡처 번역 시험하기",
            ["SnapTrans_Test_Desc"] = "화면의 영역을 선택하여 번역 테스트를 진행합니다",
            ["SnapTrans_Test_Btn"] = "영역 선택 시작",
            ["SnapTrans_ToolTip_Speak"] = "음성 읽기",
            ["SnapTrans_ToolTip_CopyTrans"] = "번역 텍스트 복사",
            ["SnapTrans_ToolTip_Close"] = "닫기",
            ["SnapTrans_Snip_Hint"] = "드래그하여 영역 선택 | Esc 취소",

            ["SwiftVolume_Name"] = "SwiftVolume",
            ["SwiftVolume_Desc"] = "작업 표시줄 트레이 아이콘, 플라이아웃 믹서, 휠 볼륨 조절 및 HUD",
            ["SwiftVolume_Subtitle"] = "작업 표시줄 트레이 아이콘, 플라이아웃 믹서, 휠 볼륨 조절 및 HUD",
            ["SwiftVolume_Enable_Desc"] = "활성화 시 작업 표시줄에 전용 스피커 아이콘이 표시되며 클릭 시 볼륨 믹서가 팝업됩니다.",
            ["SwiftVolume_ControlSection"] = "트레이 및 믹서 동작",
            ["SwiftVolume_OpenAtCursor"] = "커서 위치에 믹서 열기",
            ["SwiftVolume_OpenAtCursor_Desc"] = "트레이 아이콘 클릭 시 마우스 커서 바로 위에 믹서를 엽니다",
            ["SwiftVolume_MiddleClickMute"] = "트레이 아이콘 휠 클릭으로 음소거",
            ["SwiftVolume_MiddleClickMute_Desc"] = "스피커/마이크 트레이 아이콘을 휠 클릭 시 즉시 음소거",
            ["SwiftVolume_HudSection"] = "HUD (오버레이 표시) 설정",
            ["SwiftVolume_ShowHud"] = "음량 HUD 표시",
            ["SwiftVolume_ShowHud_Desc"] = "음량 조절 시 현재 볼륨 레벨을 세련된 HUD로 표시",
            ["SwiftVolume_ShowDeviceSwitchHud"] = "장치 변경 시 HUD 알림",
            ["SwiftVolume_ShowDeviceSwitchHud_Desc"] = "기본 스피커나 마이크 변경 시 화면에 대상 장치명을 표시",
            ["SwiftVolume_HudPosition"] = "HUD 표시 위치",
            ["SwiftVolume_HudPosition_Desc"] = "화면 중앙이나 모서리 등 HUD가 표시될 위치 선택",
            ["SwiftVolume_HudPos_Center"] = "화면 중앙",
            ["SwiftVolume_HudPos_TopCenter"] = "상단 중앙",
            ["SwiftVolume_HudPos_BottomCenter"] = "하단 중앙",
            ["SwiftVolume_HudPos_TopLeft"] = "왼쪽 상단",
            ["SwiftVolume_HudPos_TopRight"] = "오른쪽 상단",
            ["SwiftVolume_HudPos_BottomLeft"] = "왼쪽 하단",
            ["SwiftVolume_HudPos_BottomRight"] = "오른쪽 하단",
            ["SwiftVolume_HudSize"] = "HUD 크기",
            ["SwiftVolume_HudSize_Desc"] = "화면 HUD 표시의 확대/축소 크기",
            ["SwiftVolume_HudSize_Small"] = "작게",
            ["SwiftVolume_HudSize_Medium"] = "보통",
            ["SwiftVolume_HudSize_Large"] = "크게",
            ["SwiftVolume_HotkeysSection"] = "키보드 단축키 설정",
            ["SwiftVolume_Hotkey_OpenMixer"] = "볼륨 믹서 열기",
            ["SwiftVolume_Hotkey_OpenMixer_Desc"] = "플라이아웃 볼륨 믹서를 즉시 띄우는 단축키",
            ["SwiftVolume_Hotkey_Mute"] = "스피커 음소거 토글",
            ["SwiftVolume_Hotkey_Mute_Desc"] = "마스터 오디오 음소거 / 음소거 해제",
            ["SwiftVolume_Hotkey_MicMute"] = "마이크 음소거 토글",
            ["SwiftVolume_Hotkey_MicMute_Desc"] = "기본 마이크 음소거 / 음소거 해제",
            ["SwiftVolume_TestSection"] = "테스트",
            ["SwiftVolume_TestMixer_Title"] = "볼륨 믹서 테스트 표시",
            ["SwiftVolume_TestMixer_Desc"] = "화면에 볼륨 믹서 UI를 즉시 표시합니다",
            ["SwiftVolume_ShowMixerBtn"] = "믹서 표시",
            ["SwiftVolume_Mixer_Tooltip_MuteSpeaker"] = "스피커 음소거 토글",
            ["SwiftVolume_Mixer_Tooltip_Expand"] = "모든 장치 펼치기/접기",
            ["SwiftVolume_Mixer_Tooltip_MuteMic"] = "마이크 음소거 토글",
            ["SwiftVolume_Hud_SpeakerSwitch"] = "스피커 전환됨",
            ["SwiftVolume_Hud_MicSwitch"] = "마이크 전환됨",
            ["SwiftVolume_Hud_MicMuted"] = "마이크 음소거됨",
            ["SwiftVolume_Hud_MicUnmuted"] = "마이크 음소거 해제됨",
            ["SwiftVolume_Tray_Speaker"] = "SwiftVolume 스피커",
            ["SwiftVolume_Tray_Mic"] = "SwiftVolume 마이크",
            ["SwiftVolume_Tray_OpenSettings"] = "SwiftVolume 설정"
        }
    };
}
